### ISSUE TITLE
Error "/config/query not found for write. Server Message: 404 Not Found" when deploying DHF to ML database on remote server

### ISSUE THREAD

**Issue by danielholgate** [marklogic/marklogic-data-hub#1990] opened 2019-03-12 15:41 UTC
DHF 4.1.1 on local Mac,
MarkLogic 9.0.8 (also tried 9.0.8-2) running on a remote machine (Centos OS)

Deploying a simple DHF project to a new MarkLogic database on a remote machine (with mlDeploy) I get the following error: _"Error occurred while loading modules; host: usecases.demo.marklogic.com; port: 8010; cause: Local message: /config/query not found for write. Server Message: 404 Not Found"_

This problem (with exact same DHF project) does not occur when deploying to ML on local vagrant VM guest.

Databases and app servers etc are all created normally. Geert has confirmed he has seen before and thinks a network delay etc to ML communication can trip up the install mechanism. Investigated a little and we found there are no documents at all deployed to the modules database, even though the log says that they were. This is likely the root cause of this error. 

error from console log:
```
Exception in thread "ThreadPoolTaskExecutor-1" com.marklogic.client.MarkLogicIOException: java.net.SocketException: Broken pipe (Write failed)
        at com.marklogic.client.impl.OkHttpServices.sendRequestOnce(OkHttpServices.java:706)
        at com.marklogic.client.impl.OkHttpServices.sendRequestOnce(OkHttpServices.java:698)
        at com.marklogic.client.impl.OkHttpServices.doPost(OkHttpServices.java:4069)
        at com.marklogic.client.impl.OkHttpServices.postResource(OkHttpServices.java:3370)
        at com.marklogic.client.impl.OkHttpServices.postBulkDocuments(OkHttpServices.java:3478)
        at com.marklogic.client.impl.DocumentManagerImpl.write(DocumentManagerImpl.java:614)
        at com.marklogic.client.impl.GenericDocumentImpl.write(GenericDocumentImpl.java:23)
        at com.marklogic.client.impl.DocumentManagerImpl.write(DocumentManagerImpl.java:606)
        at com.marklogic.client.impl.GenericDocumentImpl.write(GenericDocumentImpl.java:23)
        at com.marklogic.client.impl.DocumentManagerImpl.write(DocumentManagerImpl.java:590)
        at com.marklogic.client.impl.GenericDocumentImpl.write(GenericDocumentImpl.java:23)
        at com.marklogic.client.ext.batch.DefaultBatchHandler.handleBatch(DefaultBatchHandler.java:54)
        at com.marklogic.client.ext.batch.RestBatchWriter$1.run(RestBatchWriter.java:80)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.net.SocketException: Broken pipe (Write failed)
        at java.net.SocketOutputStream.socketWrite0(Native Method)
        at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:111)
        at java.net.SocketOutputStream.write(SocketOutputStream.java:155)
        at okio.Okio$1.write(Okio.java:79)
        at okio.AsyncTimeout$1.write(AsyncTimeout.java:180)
        at okio.RealBufferedSink.emitCompleteSegments(RealBufferedSink.java:179)
        at okio.RealBufferedSink.write(RealBufferedSink.java:42)
        at okhttp3.internal.http1.Http1Codec$ChunkedSink.write(Http1Codec.java:334)
        at okio.ForwardingSink.write(ForwardingSink.java:35)
        at okhttp3.internal.http.CallServerInterceptor$CountingSink.write(CallServerInterceptor.java:149)
        at okio.RealBufferedSink.emitCompleteSegments(RealBufferedSink.java:179)
        at okio.RealBufferedSink$1.write(RealBufferedSink.java:201)
        at java.io.OutputStream.write(OutputStream.java:75)
        at com.marklogic.client.io.StringHandle.write(StringHandle.java:194)
        at com.marklogic.client.impl.StreamingOutputImpl.writeTo(StreamingOutputImpl.java:58)
        at okhttp3.MultipartBody.writeOrCountBytes(MultipartBody.java:173)
        at okhttp3.MultipartBody.writeTo(MultipartBody.java:114)
        at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.java:72)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:45)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
Writing default query options to MarkLogic; port: 8010; database: usecase-data-hub-STAGING
        at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
        at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:126)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
        at com.burgstaller.okhttp.AuthenticationCacheInterceptor.intercept(AuthenticationCacheInterceptor.java:45)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
        at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:200)
        at okhttp3.RealCall.execute(RealCall.java:77)
        at com.marklogic.client.impl.OkHttpServices.sendRequestOnce(OkHttpServices.java:704)
        ... 15 more

> Task :mlDeployApp
Shutting down ExecutorService
Initializing ExecutorService
Loading default query options from file default.xml
Shutting down ExecutorService

Error occurred while loading modules; host: usecases.demo.marklogic.com; port: 8010; cause: Local message: /config/query not found for write. Server Message: 404 Not Found
com.marklogic.client.ResourceNotFoundException: Local message: /config/query not found for write. Server Message: 404 Not Found
        at com.marklogic.client.impl.OkHttpServices.putPostValueImpl(OkHttpServices.java:2878)
        at com.marklogic.client.impl.OkHttpServices.putValue(OkHttpServices.java:2747)
        at com.marklogic.client.impl.QueryOptionsManagerImpl.writeOptions(QueryOptionsManagerImpl.java:158)
        at com.marklogic.client.ext.modulesloader.impl.DefaultModulesLoader.lambda$installQueryOptions$3(DefaultModulesLoader.java:546)
        at com.marklogic.client.ext.modulesloader.impl.DefaultModulesLoader.lambda$executeTask$5(DefaultModulesLoader.java:583)

> Task :mlDeployApp FAILED
:mlDeployApp (Thread[Task worker for ':',5,main]) completed. Took 2 mins 28.45 secs.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':mlDeployApp'.
> Error occurred while loading REST modules: Error occurred while loading modules; host: usecases.demo.marklogic.com; port: 8010; cause: Local message: /config/query not found for write. Server Message: 404 Not Found

* Try:
Run with --stacktrace option to get the stack trace. Run with --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 3m 4s
6 actionable tasks: 6 executed
MacPro-4133:usecases-dhf dholgate$ 
```

**Comment by danielholgate** [comment] 2019-03-12 15:48
[dhf_logging.txt](https://github.com/marklogic/marklogic-data-hub/files/2957643/dhf_logging.txt)
full log file

**Comment by danielholgate** [comment] 2019-03-12 15:51
DHF properties files [dhf-gradle-properties.zip](https://github.com/marklogic/marklogic-data-hub/files/2957656/dhf-gradle-properties.zip)

**Comment by ryanjdew** [comment] 2019-03-12 17:39
Thank you for filing an issue. An internal JIRA ticket has been created: https://project.marklogic.com/jira/browse/DHFPROD-1967

**Comment by aebadirad** [comment] 2019-03-21 22:29
@rjrudin Can you take a peek at this? I suspect its our setting up the app servers and then going through 8010 for the modules deployment. We can probably tighten this up and ensure we aren't running into a race condition with a few smart changes.

**Comment by rjrudin** [comment] 2019-03-22 12:23
DHF loads src/main/resources/ml-modules-staging/options/default.xml via port 8010. That is likely failing because the rewriter for 8010 wasn't loaded when DHF tried to load its non-REST modules, and none of them were loaded. 

So the root cause seems to be that nothing from DHF's src/main/resources/ml-modules was loaded. I can't think of a reason for that - I'd check the ML access logs to see what's reported there.

As for a race condition - ml-gradle doesn't load any REST extensions until it's completed loading the non-REST documents. All the calls to insert documents are done via the Java API.

**Comment by grtjn** [comment] 2019-03-22 17:16
I am once again hitting this issue as well. It only happens when you do a remote deployment, as if network speed is of importance somehow. I am observing these messages with -i flag:

```
Initializing ExecutorService 
Initializing ExecutorService 
Writing 18 files
Writing: /root/config/config.xqy
Writing: /root/mlpm_modules/XQuery-XML-Memory-Operations/node-operations.xqy
Writing: /root/mlpm_modules/XQuery-XML-Memory-Operations/mlpm.json
Writing: /root/mlpm_modules/XQuery-XML-Memory-Operations/memory-operations-pure-xquery.xqy
Writing: /root/mlpm_modules/XQuery-XML-Memory-Operations/memory-operations.xqy
Writing: /root/mlpm_modules/XQuery-XML-Memory-Operations/README.md
Writing: /root/mlpm_modules/XQuery-XML-Memory-Operations/memory-operations-functional.xqy
Writing: /root/lib/clueystaging2final.sjs
Writing: /root/lib/project-lib.xqy
Writing: /root/lib/cluey-lib.sjs
Writing: /entities/Incident/harmonize/HarmonizeClueyIncidents/collector.sjs
Writing: /entities/Incident/input/ImportClueyIncidents/main.sjs
Writing: /entities/Photo/harmonize/HarmonizeClueyPhotos/collector.xqy
Writing: /entities/Photo/harmonize/HarmonizeClueyPhotos/content.xqy
Writing: /entities/Photo/harmonize/HarmonizeClueyPhotos/writer.xqy
Writing: /entities/Photo/harmonize/HarmonizeClueyPhotos/main.xqy
Writing: /entities/Photo/input/ImportClueyPhotos/content.xqy
Writing: /entities/Photo/input/ImportClueyPhotos/main.xqy
Shutting down ExecutorService

Exception in thread "ThreadPoolTaskExecutor-1" com.marklogic.client.MarkLogicIOException: java.net.SocketException: Operation timed out (Read failed)
        at com.marklogic.client.impl.OkHttpServices.sendRequestOnce(OkHttpServices.java:697)
        at com.marklogic.client.impl.OkHttpServices.sendRequestOnce(OkHttpServices.java:690)
        at com.marklogic.client.impl.OkHttpServices.doPost(OkHttpServices.java:4052)
        at com.marklogic.client.impl.OkHttpServices.postResource(OkHttpServices.java:3353)
        at com.marklogic.client.impl.OkHttpServices.postBulkDocuments(OkHttpServices.java:3461)
        at com.marklogic.client.impl.DocumentManagerImpl.write(DocumentManagerImpl.java:614)
        at com.marklogic.client.impl.GenericDocumentImpl.write(GenericDocumentImpl.java:23)
        at com.marklogic.client.impl.DocumentManagerImpl.write(DocumentManagerImpl.java:606)
        at com.marklogic.client.impl.GenericDocumentImpl.write(GenericDocumentImpl.java:23)
        at com.marklogic.client.impl.DocumentManagerImpl.write(DocumentManagerImpl.java:590)
        at com.marklogic.client.impl.GenericDocumentImpl.write(GenericDocumentImpl.java:23)
        at com.marklogic.client.ext.batch.DefaultBatchHandler.handleBatch(DefaultBatchHandler.java:48)
        at com.marklogic.client.ext.batch.RestBatchWriter$1.run(RestBatchWriter.java:74)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
```

I can't escape the impression that either the writing didn't fully complete successfully, maybe because it got interrupted by a failure in a different 'thread' or such. Could there be a multi-statement transaction being rolled back?

**Comment by rjrudin** [comment] 2019-03-22 17:39
There's just one thread by default, and it's using a DocumentWriteSet from the Java API to write all the modules in one transaction. 

Link to the code: https://github.com/marklogic-community/ml-javaclient-util/blob/master/src/main/java/com/marklogic/client/ext/batch/DefaultBatchHandler.java#L37

**Comment by grtjn** [comment] 2019-03-22 19:56
Well, you know the code better than I. Shared connection object?

**Comment by grtjn** [comment] 2019-03-22 20:41
Ok, drilling a bit deeper I noticed things were going wrong within a step called LoadHubModulesCommand, which seems to be part of hubInstallModules. It is something that surfaced for DHF4, but I'm seeing with a version as old as v2.0.4 as well!

Here a comment in which Damon attempts to describe it. https://github.com/marklogic/marklogic-data-hub/issues/1378#issuecomment-428333818 There is a workaround in there too.

**Comment by grtjn** [comment] 2019-03-22 20:41
Hmm, interesting. Supposed to be fixed in 4.1.0, but @danielholgate is using 4.1.1?

**Comment by danielholgate** [comment] 2019-03-26 08:08
Correct @grtjn . I also tested on latest DHF 4.2.1 and got the same error

**Comment by rjrudin** [comment] 2019-05-28 18:42
@danielholgate Did this ever start working for you?

**Comment by danielholgate** [comment] 2019-05-28 18:54
@rjrudin no it didn't.. I just worked around it by copying the entire DHF project to the target machine and running the tasks there with mlHost = localhost. A few others noted this same error as well, so sounds like it's still out there. Easy to reproduce btw :)

**Comment by smazerml** [comment] 2019-05-28 18:57
seeing it as well. Are you using a demo machine hosted by MarkLogic @danielholgate ?

**Comment by danielholgate** [comment] 2019-05-28 19:01
@smazerml Indeed I am! IT provisioned a machine for me to deploy a DHF+Grove app to and that's when I first came across this ongoing problem

**Comment by smazerml** [comment] 2019-05-28 19:02
I suspect it has to do with our demo server configuration. I'd be curious if others see it if deploying to EC2

**Comment by smazerml** [comment] 2019-05-28 19:03
and for the record, we are using DHF 5.0

**Comment by danielholgate** [comment] 2019-05-28 19:05
Tim Taylor reported seeing it on Azure

**Comment by smazerml** [comment] 2019-05-28 19:06
@danielholgate @rjrudin has a hack to copy modules via mlcp/xcc we should probably distribute out

**Comment by ayuwono** [comment] 2019-05-28 19:10
Similar issue

We have this on jenkins machine too when running QuickStart UI test. https://project.marklogic.com/jira/browse/DHFPROD-2433

We're able to capture the screenshot that installation is always stuck on:
45% progress appears to be step 21 (LoadHubModulesCommand)

[Step 21 of 44] com.marklogic.hub.deploy.commands.LoadHubModulesCommand
java.lang.RuntimeException: Error occurred while loading REST modules: Error occurred while loading modules; host: localhost; port: 8010; cause: java.net.ConnectException: Failed to connect to localhost/0:0:0:0:0:0:0:1:8010

**Comment by aebadirad** [comment] 2019-06-15 19:39
This maybe related to a deeper Java-api-client bug that we have yet to uncover. We've added batch setting capability now so this is as much as we can do in this project, closing based on #2604

**Closed by aebadirad** 2019-06-15 19:39 UTC
