### ISSUE TITLE
Primary key is not retained if it's clicked first when adding a property

### ISSUE THREAD

**Issue by ayuwono** [marklogic/marklogic-data-hub#679] opened 2018-01-23 22:36 UTC
On the tutorial for:
https://marklogic-community.github.io/marklogic-data-hub/tutorial/modeling-product-entity

It says to select the primary key first then the property name.
If you do this, the primary key icon will disappear after you enter the property name.

If you enter the property name first then click the primary key, the primary key icon will retain .

Which Operating System are you using?
Mac OSX

Which version of MarkLogic are you using?
9.0-nightly

Which version of the Data Hub Framework are you using?
2.0.2

Is this a QuickStart UI bug? If so, which browser are you using?
Chrome

┆Status: Done

**Comment by dmcassel** [comment] 2018-04-04 18:39
➤ Alexander Ebadirad commented:

This may be related between saving of indexes/properties from quickstart gui to marklogic server.

Verify that quickstart is saving the information locally in the proper json file on disk for the entity, then that the deployment of the primary key/matching index occurs.

**Comment by dmcassel** [comment] 2018-04-12 14:14
➤ Mike Wooldridge commented:

I've confirmed the behavior that Aries reports and am investigating.

**Comment by dmcassel** [comment] 2018-04-12 14:24
➤ Mike Wooldridge commented:

This happens with the other property settings as well -- i.e, Element Range Index, Path Range Index, etc. If you select one of these settings first and then click into the Name field, upon typing a name the setting selections disappear.

**Comment by dmcassel** [comment] 2018-04-12 15:14
➤ Mike Wooldridge commented:

This issue has to do with how a new or edited entity's state is maintained in the browser (Angular), not with any saving/retrieving of entity information from disk or from the database. This is because entity information is only saved to disk when the "Save" button is clicked in the entity editing dialog.

Currently, the primary key for an entity is set with the name of the primary key property. 

If you set the primary key when the property has no name (as in [~ayuwono]'s example), the primary key is set as undefined. When you then go set the name of the property, the primary key and the name for that property no longer match, so the primary key setting for that property disappears (the bug). 

Linking the primary key with the name results in other bugs as well:

1. Click the "+" twice to create two empty properties.
2. Select one of the properties as the primary key.
3. Both properties have the key icon appear since both have undefined names (and undefined is now the primary key).

Or:

1. Give two properties the same name (e.g., "foo").
2. Select one of the properties as the primary key.
3. Both "foo" properties have the key icon appear since both have "foo" names.

We are seeing similar problems with the Element Range Index and other settings because they too are linked to a property's name. 

A solution to all this would be to associate the primary key (and similar settings) with a unique (hidden) ID associated with each property instead of each property's name.

Another issue to consider is whether to restrict the user from creating an entity that has multiple properties with the same name. Currently the user can do this.

**Comment by dmcassel** [comment] 2018-04-20 07:34
➤ Mike Wooldridge commented:

Fix in PR here: https://github.com/marklogic/marklogic-data-hub/pull/900

**Comment by dmcassel** [comment] 2018-04-23 21:14
➤ Aries Yuwono commented:

Verified passed on QA (will modify the e2e test)

**Comment by aebadirad** [comment] 2018-05-03 15:51
Fixed with release of 3.0.0

**Closed by aebadirad** 2018-05-03 15:51 UTC
Labels: Component:QuickStart, Documentation, Fixed in Dev, bug, priority:high
