### ISSUE TITLE
DHF 5.1 - Batch size and thread count changes are not being recognized. 

### ISSUE THREAD

**Issue by sundarbandepalli** [marklogic/marklogic-data-hub#3587] opened 2020-02-17 20:37 UTC
Issue - Batch size and thread count changes are not being recognized. DHF v 5.1

I changed the batch size and thread count to 1 so that parallel processing will be disabled. I have a data set of 35K customers with only 7K approx. unique customer ID values. 

What are the steps to reproduce the issue:
1) Make the changes to the above values and DHF job will keep spinning with conflicting updates error messages
2) Everything is good when you run the command from the command prompt using ./gradlew and flow name and other necessary parameters.

#### Tech details

Which Operating System are you using?
Mac
Which version of MarkLogic are you using?
10.0-20191127
Which version of the Data Hub are you using?
5.1
Is this a QuickStart UI bug? If so, which browser are you using?
Yes, Chrome. 
#### The devil is in the details...

If possible, rerun the command with -d for debugging output and attach the output:

  **for quickstart:**  
  `java -jar marklogic-datahub-<version>.war  --debug  > myoutput.txt`

  **for gradle:**  
  `gradle mlYourCommand -debug > myoutput.txt`
2020-02-17 14:12:11.560 Info: Status 500: XDMP-CONFLICTINGUPDATES: xdmp.documentInsert("/Customer/2772.json", ObjectNode({"envelope":{"headers":{"sources":[{"name":"IngestCustomers"}], "createdOn":"...", ...}, ...}}), {permissions:[{capability:"read", roleId:"7089338530631756591"}, {capability:"update", roleId:"15520654661378671735"}], collections:["OracleCustomerMapping", "Customer"], metadata:{datahubCreatedBy:"admin", datahubCreatedByStep:"OracleCustomerMapping", datahubCreatedInFlow:"CustMapping", ...}}) -- Conflicting updates xdmp.documentInsert("/Customer/2772.json", ObjectNode({"envelope":{"headers":{"sources":[{"name":"IngestCustomers"}], "createdOn":"...", ...}, ...}}), (Element("<sec:permission xmlns:sec='http://marklogic.com/xdmp/security'><sec:capability>read</sec:capability><sec:role-id>7089338530631756591</sec:role-id></sec:permission>"), Element("<sec:permission xmlns:sec='http://marklogic.com/xdmp/security'><sec:capability>update</sec:capability><sec:role-id>15520654661378671735</sec:role-id></sec:permission>")), ("OracleCustomerMapping", "Customer"), 0) and xdmp.documentInsert("/Customer/2772.json", ObjectNode({"envelope":{"headers":{"sources":[{"name":"IngestCustomers"}], "createdOn":"...", ...}, ...}}), (Element("<sec:permission xmlns:sec='http://marklogic.com/xdmp/security'><sec:capability>read</sec:capability><sec:role-id>7089338530631756591</sec:role-id></sec:permission>"), Element("<sec:permission xmlns:sec='http://marklogic.com/xdmp/security'><sec:capability>update</sec:capability><sec:role-id>15520654661378671735</sec:role-id></sec:permission>")), ("OracleCustomerMapping", "Customer"), 0)

**Comment by rjrudin** [comment] 2020-02-17 21:33
What kind of step - ingestion, or something else? 

If the issue is only in QuickStart, it is not likely to be fixed.

**Comment by sundarbandepalli** [comment] 2020-02-17 21:43
Custom step, moving data from staging to final.

**Comment by rjrudin** [comment] 2021-03-08 03:22
Closing as it sounds like it was specific to QS (if it is still an issue).

**Closed by rjrudin** 2021-03-08 03:22 UTC
