### ISSUE TITLE
[BUG] mlDeploy fails stating "Unable to get version of MarkLogic; cause: 401 Unauthorized"

### ISSUE THREAD

**Issue by s3-4v** [marklogic/marklogic-data-hub#5336] opened 2021-03-09 20:11 UTC
Since following the upgrade procedure to update DHF from 5.2.2 to 5.4, mlDeploy fails stating "Unable to get version of MarkLogic; cause: 401 Unauthorized" -- after that happens, running mlLoadModules effectively fails, until one runs tasks like mlDeployDatabases and mlDeployServers and some other deployment tasks seen in mlDeploy --dry-run so that the deployment essentially completes.

Still the problem remains that running mlDeploy ends with mlDeployApp failing with the following:

> Execution failed for task ':mlDeployApp'.
> > Unable to get version of MarkLogic; cause: 401 Unauthorized: [{"errorResponse":   {"statusCode":401,
>      "status":"Unauthorized",
>      "message":"401 Unauthorized"
>     }
>   }]
> 

I tried setting mlServerVersion=10 in gradle.properties, just in case, didn't help.

I am able to authenticate with the Management API using the same credentials just fine, and it runs for 11 minutes, presumably successfully authenticating many times before this.

Please let me know if I can provide more information to assist you.

This is with Gradle 6.2.2 on Windows 10 Pro 2004, DHF 5.4, MarkLogic 10.0-6 on CentOS 7.9.2009.

Thank you.

_Originally posted by @s3-4v in https://github.com/marklogic/marklogic-data-hub/issues/5335#issuecomment-794385427_

**Comment by s3-4v** [comment] 2021-03-09 20:33
@rjrudin We're setting mlStagingPort in several env-specific properties files including local and referencing using token substitution in ml-config and hub-internal-config -- but we're not setting mlStagingPort specifically in gradle.properties.

As to mlAppServicesPort, in this project it only appears in gradle.properties but is commented-out.

**Comment by rjrudin** [comment] 2021-03-09 20:45
Can you run it again with "--stacktrace" and paste the first 5 lines or so in (don't need the full stacktrace, just need the first few lines).

**Comment by s3-4v** [comment] 2021-03-09 21:13
Running `./gradlew mlDeploy -PenvironmentName=int --stacktrace`.....

(Please note I've tried Gradle 6.2.2, 6.3 and 6.4 in the Wrapper.)

> > Task :mlDeployApp
> Logging HTTP response body to assist with debugging: {"errorResponse":   {"statusCode":401,
>    "status":"Unauthorized",
>    "message":"401 Unauthorized"
>   }
> }
> Unable to determine the server version; cause: Unable to get version of MarkLogic; cause: 401 Unauthorized: [{"errorResponse":   {"statusCode":401,
>    "status":"Unauthorized",
>    "message":"401 Unauthorized"
>   }
> }]
> Will set mlServerVersion to 9 as a fallback

Please note the "Will set mlServerVersion to 9 as a fallback" part.

Followed by many repeated notices:

> Unable to store properties, cause: int-C:\ASR\revhub\marklogic\build\ml-javaclient-util\module-timestamps.properties (The filename, directory name, or volume label syntax is incorrect)
> null

Then:

> Execution failed for task ':mlDeployApp'.
> > Unable to get version of MarkLogic; cause: 401 Unauthorized: [{"errorResponse":   {"statusCode":401,
>      "status":"Unauthorized",
>      "message":"401 Unauthorized"
>     }
>   }]
> 
> * Try:
> Run with --info or --debug option to get more log output. Run with --scan to get full insights.
> 
> * Exception is:
> org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':mlDeployApp'.
>         at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.lambda$executeIfValid$1(ExecuteActionsTaskExecuter.java:205)
>         at org.gradle.internal.Try$Failure.ifSuccessfulOrElse(Try.java:263)
>         at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeIfValid(ExecuteActionsTaskExecuter.java:203)
>         at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:184)
>         at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:114)
>         at org.gradle.api.internal.tasks.execution.FinalizePropertiesTaskExecuter.execute(FinalizePropertiesTaskExecuter.java:46)
>         at org.gradle.api.internal.tasks.execution.ResolveTaskExecutionModeExecuter.execute(ResolveTaskExecutionModeExecuter.java:62)
>         at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:57)
>         at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:56)
>         at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:36)
>         at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.executeTask(EventFiringTaskExecuter.java:77)

[....]

And:

> Caused by: java.lang.RuntimeException: Unable to get version of MarkLogic; cause: 401 Unauthorized: [{"errorResponse":   {"statusCode":401,
>    "status":"Unauthorized",
>    "message":"401 Unauthorized"
>   }
> }]
>         at com.marklogic.hub.MarkLogicVersion.getMarkLogicVersionString(MarkLogicVersion.java:152)
>         at com.marklogic.hub.MarkLogicVersion.<init>(MarkLogicVersion.java:39)
>         at com.marklogic.hub.deploy.commands.CreateGranularPrivilegesCommand.execute(CreateGranularPrivilegesCommand.java:132)
>         at com.marklogic.appdeployer.impl.AbstractAppDeployer.executeCommand(AbstractAppDeployer.java:101)
>         at com.marklogic.appdeployer.impl.AbstractAppDeployer.deploy(AbstractAppDeployer.java:85)
>         at com.marklogic.appdeployer.AppDeployer$deploy.call(Unknown Source)
>         at com.marklogic.gradle.task.DeployAppTask.deployApp(DeployAppTask.groovy:32)
>         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
>         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
>         at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

Please let me know what else I can do to help.

Thank you.

**Comment by rjrudin** [comment] 2021-03-09 22:17
Haven't been able to reproduce yet. Are you able to share your project? You could likely exclude flows/entities/steps/mappings. You can use hubExportProject. 

If you are a licensed customer, you can open a support ticket too if you'd rather submit the project via our Support system instead of github.

**Comment by rjrudin** [comment] 2021-03-24 18:28
Closing due to existence of a support ticket (same as for #5335).

**Closed by rjrudin** 2021-03-24 18:28 UTC
