### ISSUE TITLE
Entities rendering: link is unstable

### ISSUE THREAD

**Issue by sbuxton** [marklogic/marklogic-data-hub#863] opened 2018-04-04 23:20 UTC
#### The issue

Following the Quickstart Tutorial, when I have Products + Orders under the Entities tab, the link between the two is unstable.
If I move the Orders box around, the link switches between:
-- no link
-- link with no arrow, no label
-- link with arrow, no label, does not reach the Products box
-- link with arrow, label 1..INF, reaches Product box

#### Tech details

Which Operating System are you using?
Linux
Which version of MarkLogic are you using?
9.0-4 nightly
Which version of the Data Hub Framework are you using?
2.0.4
Is this a QuickStart UI bug? If so, which browser are you using?
Chrome on Windows

**Comment by aebadirad** [comment] 2018-09-15 22:04
Duplicate of issue #806 so closing to consolidate issues

**Closed by aebadirad** 2018-09-15 22:04 UTC
Labels: Component:QuickStart
