### ISSUE TITLE
JSON wizard creates XML code template

### ISSUE THREAD

**Issue by damonfeldman** [marklogic/marklogic-data-hub#1393] opened 2018-10-05 18:06 UTC
#### The issue

I selected JSON/JavaScript in the create entity dialog, but got code including "NodeBuilder" and other XML functions.

What behavior are you expecting?
Pure JavaScript/JSON code.

#### Tech details

Which Operating System are you using?
OSX

Which version of MarkLogic are you using?
9.0-5

Which version of the Data Hub Framework are you using?
4.0.0 (quickstart)

Is this a QuickStart UI bug? If so, which browser are you using?
Not sure.

here is the dialog to create the (input) flow:
![image](https://user-images.githubusercontent.com/700633/46552149-d39a5280-c8a7-11e8-9d62-9c685fefbb27.png)

Here is the generated code for content.sjs
```
'use strict'

/*
* Create Content Plugin
*
* @param id         - the identifier returned by the collector
* @param options    - an object containing options. Options are sent from Java
*
* @return - your content
*/
function createContent(id, rawContent, options) {
  

  let source;

  // for xml we need to use xpath
  if(rawContent && xdmp.nodeKind(rawContent) === 'element' && rawContent instanceof XMLDocument) {
    source = rawContent
  }
  // for json we need to return the instance
  else if(rawContent && rawContent instanceof Document) {
    source = fn.head(rawContent.root);
  }
  // for everything else
  else {
    source = rawContent;
  }

  return extractInstanceMember(source);
}
  
/**
* Creates an object instance from some source document.
* @param source  A document or node that contains
*   data for populating a member
* @return An object with extracted data and
*   metadata about the instance.
*/
function extractInstanceMember(source) {
  let attachments = source;
  // now check to see if we have XML or json, then create a node clone to operate of off
  if (source instanceof Element || source instanceof ObjectNode) {
    let instancePath = '/';
    if(source instanceof Element) {
      //make sure we grab content root only
      instancePath = '/node()[not(. instance of processing-instruction() or . instance of comment())]';
    }
    source = new NodeBuilder().addNode(fn.head(source.xpath(instancePath))).toNode();
  }
  else{
    source = new NodeBuilder().addNode(fn.head(source)).toNode();
  }
  let medicaidID = !fn.empty(fn.head(source.xpath('/medicaidID'))) ? xs.string(fn.head(fn.head(source.xpath('/medicaidID')))) : null;

  // return the instance object
  return {
    '$attachments': attachments,
    '$type': 'member',
    '$version': '0.0.1',
    'medicaidID': medicaidID
  }
};


function makeReferenceObject(type, ref) {
  return {
    '$type': type,
    '$ref': ref
  };
}

module.exports = {
  createContent: createContent
};

```

**Comment by aebadirad** [comment] 2018-10-05 21:03
As of 4.0.0, we now default set everything as a node (xmldoc/element for XML or objectNode or Document for JSON).

The data format is what the output result of the flow will be in and what format the traces will be in as well. This is designed to work for either xml or json inputs (or both if the formats mirror tree structure), as this provides a universal xpathing for documents that match our indexing strategy as well.

If you're wanting plain object, you can always .toObject the response :)

Perhaps we can be clearer on that in the documentation.

**Comment by grechaw** [comment] 2018-10-09 21:08
This is by design, I'll close the issue just to clean it up but happy to talk about the codegen onwards into the future.

**Closed by grechaw** 2018-10-09 21:08 UTC
