### ISSUE TITLE
Search not property scoped

### ISSUE THREAD

**Issue by sjcrook** [marklogic/marklogic-data-hub#3102] opened 2019-10-18 20:47 UTC
/com.marklogic.smart-mastering/matcher-impl/matcher-impl.xqy, function match-impl:values-by-qname

The line in the function, ...

let $values := fn:distinct-values($document//*[fn:node-name(.) eq $qname] ! fn:normalize-space(fn:string(.))[.])

...isn't property scoped.  If there are other property names outside of the entity, they'll (erroneously, I believe) match.  I believe the line should be...

let $values := fn:distinct-values($document//envelope/instance/*[fn:node-name(.) eq $qname] ! fn:normalize-space(fn:string(.))[.])

**Comment by sjcrook** [comment] 2019-10-18 21:10
Correction...

... $document/envelope/instance//* etc.

**Comment by crism** [comment] 2019-10-21 18:34
Duplicate of #3090.

**Comment by rjrudin** [comment] 2021-03-07 15:00
Closing since it's a dupe of 3090

**Closed by rjrudin** 2021-03-07 15:00 UTC
