### ISSUE TITLE
Enhancement: No need for Hub Config with Java SDK

### ISSUE THREAD

**Issue by awanczowski** [marklogic/marklogic-data-hub#3097] opened 2019-10-18 19:12 UTC
Short description of the problem: Currently there is a need to point to the data hub configurations locally. Ideally, the SDK would ping MarkLogic to get the configs.

**Comment by sbayatpur** [comment] 2019-10-31 19:31
Thanks, @awanczowski. Can you please explain more about why the workflow we support today is creating difficulties, and how your suggestion would make things easier for you?

**Comment by awanczowski** [comment] 2019-11-01 21:14
Hi @sbayatpur, you need the configurations from the data hub project to be available to the Java API. https://docs.marklogic.com/datahub/flows/run-flow-using-datahub-api.html

It is a bit cumbersome  if we want to maintain a separate repository for the Java Code, we either have to checkout the DataHub config to a separate directory and reference or have it as a submodule in our git project.

**Comment by jmakeig** [comment] 2019-11-01 23:15
Ping @rjrudin.

**Comment by rjrudin** [comment] 2019-11-08 19:09
@sbayatpur @awanczowski This is the root problem for why I say we don't have a good story for running a flow in production. 

We provide 5 options in our docs - Using QuickStart, Using Gradle, Using REST Client API, Using Data Hub API, and Using MLCP. Our docs say not to use QS. Gradle and the Data Hub API both require a DH project to be referenceable on the filesystem - in effect requiring a project's source code to be available on disk in a production system, which is the problem being pointed out here. MLCP is only useful for ingest. And so the REST Client API is the only viable solution, but that means the customer is on their own for running flows, as the "runFlow" endpoint doesn't actually run a flow - it just processes a batch of URIs for a single step. 

My goal is that in the Q4 release, by trying to develop a client that can be used to run a step or a flow in a context like NiFi, we will achieve what this ticket is asking for - i.e. a Data Hub SDK that doesn't depend on a DH project being accessible on a filesystem.

**Comment by rjrudin** [comment] 2019-11-08 19:10
Pinging @josvanroosmalen , as this is basically a duplicate of #1521. One of these should thus be closed.

**Comment by rjrudin** [comment] 2021-03-07 14:59
I believe this has been addressed in 5.2 where a run flow can be run without the project being available on the filesystem

**Closed by rjrudin** 2021-03-07 14:59 UTC
Labels: Enhancement
