### ISSUE TITLE
DHF 5.0.0: Mastering on old entity configuration

### ISSUE THREAD

**Issue by prestonmcgowan** [marklogic/marklogic-data-hub#2496] opened 2019-05-13 18:24 UTC
#### The issue
My "Location" data was causing DHF to throw errors for some reason. Given I just wanted to see some data, i removed the offending item from my entity. I ran the mastering process and noticed I was still receiving failures. When I look at the error, I see it is still trying to process my entity's item.

`{"stack":"Error: Could not find a target entity: /location/Location-0.0.1/Location\n at Error (native)\n at main (/data-hub/5/builtins/steps/mapping/default/main.sjs:71:11)\n at Flow.runMain (/data-hub/5/impl/flow.sjs:374:12)\n at Flow.runStep (/data-hub/5/impl/flow.sjs:319:60)\n at Flow.runFlow (/data-hub/5/impl/flow.sjs:202:12)\n at post (/data-hub/5/extensions/runFlow.sjs:69:25)\n at callExtension (/data-hub/5/rest-api/lib/extensions-util.sjs:94:30)\n at applyOnce (/data-hub/5/rest-api/lib/extensions-util.sjs:112:10)","message":"Could not find a target entity: /location/Location-0.0.1/Location","name":"Error"}`

Entity:
![image](https://user-images.githubusercontent.com/1315891/57644732-bf7ba980-758a-11e9-9532-5fde6d930ad2.png)

Flow:
![image](https://user-images.githubusercontent.com/1315891/57644703-b38fe780-758a-11e9-9d18-2731800c9af8.png)

#### Tech details

Which Operating System are you using?
Mac 10.14.4 (18E226)

Which version of MarkLogic are you using?
9.0-9

Which version of the Data Hub Framework are you using?
5.0.0

Is this a QuickStart UI bug? If so, which browser are you using?
No

**Comment by prestonmcgowan** [comment] 2019-05-13 18:38
I deleted all of the data in staging, jobs, and final with the 💀
I redeployed the application with the "Redeploy" button.
I ran the whole flow to ingest and master the data.
Failed with the same error, even with the location no longer in my entity or flow.

**Comment by ayuwono** [comment] 2019-05-13 18:40
Just curious, what happened if you run ingestion after removing the entity prop and then run mapping

Which redeploy button did you use? After clearing all DBs, you should run Redeploy Hub from the Settings page, not redeploy from Flows page

**Comment by prestonmcgowan** [comment] 2019-05-13 18:42
I had not tried to rerun ingestion.

I redeployed with the Redeploy in the Flows page.

**Comment by prestonmcgowan** [comment] 2019-05-13 18:45
I seem to have four mappings documents in the Final database. Is this expected?

`[{"uri":"/mappings/ZipCodes-Create-zips/ZipCodes-Create-zips-0.mapping.json", "contents":{"language":"zxx", "name":"ZipCodes-Create-zips", "description":"", "version":0, "targetEntityType":"/locationLocation-0.0.1/Location", "sourceContext":"//", "sourceURI":"", "properties":{}}}, {"uri":"/mappings/ZipCodes-Create-zips/ZipCodes-Create-zips-1.mapping.json", "contents":{"language":"zxx", "name":"ZipCodes-Create-zips", "description":"", "version":1, "targetEntityType":"/locationLocation-0.0.1/Location", "sourceContext":"//", "sourceURI":"/Users/pmcgowan/Projects/DHF%205.0/data/6c373d20-f435-4288-84f4-08a92c9cedb9.json", "properties":{"zipCode":{"sourcedFrom":"Zipcode"}, "country":{"sourcedFrom":"Country"}, "decommissioned":{"sourcedFrom":"Decommisioned"}, "detailedLocation":{"sourcedFrom":"LocationText"}, "city":{"sourcedFrom":"City"}, "lon":{"sourcedFrom":"Long"}, "location":{"sourcedFrom":"Location"}, "state":{"sourcedFrom":"State"}, "lat":{"sourcedFrom":"Lat"}}}}, {"uri":"/mappings/ZipCodes-Create-zips/ZipCodes-Create-zips-2.mapping.json", "contents":{"language":"zxx", "name":"ZipCodes-Create-zips", "description":"", "version":2, "targetEntityType":"/location/Location-0.0.1/Location", "sourceContext":"//", "sourceURI":"/Users/pmcgowan/Projects/DHF%205.0/data/6c373d20-f435-4288-84f4-08a92c9cedb9.json", "properties":{"zipCode":{"sourcedFrom":"Zipcode"}, "country":{"sourcedFrom":"Country"}, "decommissioned":{"sourcedFrom":"Decommisioned"}, "detailedLocation":{"sourcedFrom":"LocationText"}, "city":{"sourcedFrom":"City"}, "lon":{"sourcedFrom":"Long"}, "state":{"sourcedFrom":"State"}, "lat":{"sourcedFrom":"Lat"}}}}, {"uri":"/mappings/ZipCodes-Create-zips/ZipCodes-Create-zips-3.mapping.json", "contents":{"language":"zxx", "name":"ZipCodes-Create-zips", "description":"", "version":3, "targetEntityType":"/location/Location-0.0.1/Location", "sourceContext":"//", "sourceURI":"/Users/pmcgowan/Projects/DHF%205.0/data/6c373d20-f435-4288-84f4-08a92c9cedb9.json", "properties":{"country":{"sourcedFrom":"Country"}, "decommissioned":{"sourcedFrom":"Decommisioned"}, "zipCode":{"sourcedFrom":"Zipcode"}, "detailedLocation":{"sourcedFrom":"LocationText"}, "city":{"sourcedFrom":"City"}, "lon":{"sourcedFrom":"Long"}, "state":{"sourcedFrom":"State"}, "lat":{"sourcedFrom":"Lat"}}}}]`

**Comment by ayuwono** [comment] 2019-05-13 18:45
Ok, run redeploy hub from Settings page. It will bring all your flows, entities, and mappings config. Then after removing that entity prop, rerun the ingestion then mapping

**Comment by ayuwono** [comment] 2019-05-13 18:47
Yes, mapping configs wil be stored in Final DB

**Comment by prestonmcgowan** [comment] 2019-05-13 18:47
I just clicked the skull icon and clicked redeploy hub from the settings page.

UI ISSUE: There is no way of knowing your status unless you have the DevTools open.
![image](https://user-images.githubusercontent.com/1315891/57646211-0dde7780-758e-11e9-8f08-91fab07fb789.png)

**Comment by ayuwono** [comment] 2019-05-13 18:52
That's odd, might be intermittent issue. I never seen that before, I usually can see the status

**Comment by prestonmcgowan** [comment] 2019-05-13 18:59
Mapping is still failing.

`{"stack":"Error: Could not find a target entity: /location/Location-0.0.1/Location\n at Error (native)\n at main (/data-hub/5/builtins/steps/mapping/default/main.sjs:71:11)\n at Flow.runMain (/data-hub/5/impl/flow.sjs:374:12)\n at Flow.runStep (/data-hub/5/impl/flow.sjs:319:60)\n at Flow.runFlow (/data-hub/5/impl/flow.sjs:202:12)\n at post (/data-hub/5/extensions/runFlow.sjs:69:25)\n at callExtension (/data-hub/5/rest-api/lib/extensions-util.sjs:94:30)\n at applyOnce (/data-hub/5/rest-api/lib/extensions-util.sjs:112:10)","message":"Could not find a target entity: /location/Location-0.0.1/Location","name":"Error"}`

**Comment by srinathgit** [comment] 2019-05-13 19:03
The issue is with the value of 'targetEntityType' property in mapping. Can you provide a valid IRIR something like "http://example.org/Location-0.0.1/Location" and let me know if it works ? Also make sure /entities/Location.entity.json is present in staging db

**Comment by prestonmcgowan** [comment] 2019-05-13 19:06
Where in the UI would I set that?

**Comment by prestonmcgowan** [comment] 2019-05-13 19:07
Database: **data-hub-5.0-STAGING**
QConsole:
`fn.doc('/entities/Location.entity.json')`

Returns:
`{"info":{"title":"Location", "version":"0.0.1", "baseUri":"/location/"}, "definitions":{"Location":{"required":[], "pii":[], "elementRangeIndex":["city", "state", "decommissioned"], "rangeIndex":[], "wordLexicon":[], "properties":{"zipCode":{"datatype":"integer"}, "city":{"datatype":"string", "collation":"http://marklogic.com/collation/codepoint"}, "state":{"datatype":"string", "collation":"http://marklogic.com/collation/codepoint"}, "lat":{"datatype":"float"}, "lon":{"datatype":"float"}, "country":{"datatype":"string", "collation":"http://marklogic.com/collation/codepoint"}, "detailedLocation":{"datatype":"string", "collation":"http://marklogic.com/collation/codepoint"}, "decommissioned":{"datatype":"boolean"}}}}}`

**Comment by srinathgit** [comment] 2019-05-13 19:18
@prestonmcgowan ,
The reason why a valid 'targetEntityType' is not getting set in the mapping is because the entity is not a valid ES model. If you run es.modelValidate() on the entity you provided, it would fail. Can you use this entity (check the baseUri property) , deploy it and use it to create mapping and run it ?

```
{
	"info": {
		"title": "Location",
		"version": "0.0.1",
		"baseUri": "http://example.org/"
	},
	"definitions": {
		"Location": {
			"required": [],
			"pii": [],
			"elementRangeIndex": ["city", "state", "decommissioned"],
			"rangeIndex": [],
			"wordLexicon": [],
			"properties": {
				"zipCode": {
					"datatype": "integer"
				},
				"city": {
					"datatype": "string",
					"collation": "http://marklogic.com/collation/codepoint"
				},
				"state": {
					"datatype": "string",
					"collation": "http://marklogic.com/collation/codepoint"
				},
				"lat": {
					"datatype": "float"
				},
				"lon": {
					"datatype": "float"
				},
				"country": {
					"datatype": "string",
					"collation": "http://marklogic.com/collation/codepoint"
				},
				"detailedLocation": {
					"datatype": "string",
					"collation": "http://marklogic.com/collation/codepoint"
				},
				"decommissioned": {
					"datatype": "boolean"
				}
			}
		}
	}
}
```

**Comment by ayuwono** [comment] 2019-05-13 19:21
Can you check on UI, go to your mapping step. Click on edit settings (the three dots). On advanced setttings, do you see the databases are getting selected? It could be after redeploy hub, the settings are lost

**Comment by prestonmcgowan** [comment] 2019-05-13 19:23
![image](https://user-images.githubusercontent.com/1315891/57648292-15544f80-7593-11e9-9aa2-54e43891d406.png)

**Comment by prestonmcgowan** [comment] 2019-05-13 19:24
@ayuwono , did you mean to put that comment in Issue 2497?

**Comment by prestonmcgowan** [comment] 2019-05-13 19:33
@srinathgit, I updated the base URI as you suggested using the Quick Start UI's entity editor.
I was then able to execute the mapping stage.
Sadly, it looks like everything in the headers was set to null. Potentially because of issue 2497

**Comment by srinathgit** [comment] 2019-05-13 19:36
I will now close this issue since you were able to run the flow.

**Closed by srinathgit** 2019-05-13 19:36 UTC
Labels: 5.0
