### ISSUE TITLE
[BUG] Conflicting updates in QuickStart after editing custom hook settings in mapping step

### ISSUE THREAD

**Issue by fsnow** [marklogic/marklogic-data-hub#3643] opened 2020-03-03 20:15 UTC
#### The issue

When QuickStart deploys a custom hooks module, it is failing with an XDMP-CONFLICTINGUPDATES error. Console output below.

What are the steps to reproduce the issue:
1) Edit custom hook settings, click Save
2) Watch QuickStart console

#### Tech details

Data Hub 5.2-rc1
Windows 10
Chrome 80.0.3987.122

14:55:29.526 [SimpleAsyncTaskExecutor-9] INFO  c.m.h.d.c.LoadUserModulesCommand - Loading modules from paths: [F:\MarkLogic\Proj\data-hub\src\main\ml-modules]
2020-03-03 14:55:31.411 ERROR 4372 --- [TaskExecutor-10] .a.i.SimpleAsyncUncaughtExceptionHandler : Unexpected exception occurred invoking async method: public void com.marklogic.hub.web.service.DataHubService.installUserModulesAsync(com.marklogic.hub.HubConfig,boolean,com.marklogic.hub.web.listeners.DeployUserModulesListener,com.marklogic.hub.web.listeners.ValidateListener)

com.marklogic.hub.web.exception.DataHubException: Error in connecting to the Data Hub API with the following message: Local message: failed to apply resource at documents: Bad Request. Server Message: XDMP-CONFLICTINGUPDATES: xdmp:document-insert("/custom-modules/custom-hooks/setMappedColl.sjs", document{text{"declareUpdate();&#13;&#10;&#13;&#10;// A custom hook receives..."}}, <options xmlns="xdmp:document-insert"><permissions><sec:permission .../>...</permissions></options>) -- Conflicting updates xdmp:document-insert("/custom-modules/custom-hooks/setMappedColl.sjs", document{text{"declareUpdate();&#13;&#10;&#13;&#10;// A custom hook receives..."}}, (<sec:permission xmlns:sec="http://marklogic.com/xdmp/security"><sec:capability>update</sec:capability><sec:role-id>7981934846638917044</sec:role-id></sec:permission>, <sec:permission xmlns:sec="http://marklogic.com/xdmp/security"><sec:capability>execute</sec:capability><sec:role-id>13041542794130379697</sec:role-id></sec:permission>, <sec:permission xmlns:sec="http://marklogic.com/xdmp/security"><sec:capability>read</sec:capability><sec:role-id>17997362789601553516</sec:role-id></sec:permission>, <sec:permission xmlns:sec="http://marklogic.com/xdmp/security"><sec:capability>execute</sec:capability><sec:role-id>17997362789601553516</sec:role-id></sec:permission>, <sec:permission xmlns:sec="http://marklogic.com/xdmp/security"><sec:capability>update</sec:capability><sec:role-id>15080714410678341621</sec:role-id></sec:permission>, <sec:permission xmlns:sec="http://marklogic.com/xdmp/security"><sec:capability>read</sec:capability><sec:role-id>15080714410678341621</sec:role-id></sec:permission>), (), 0) and xdmp:document-insert("/custom-modules/custom-hooks/setMappedColl.sjs", document{text{"declareUpdate();&#13;&#10;&#13;&#10;// A custom hook receives..."}}, (<sec:permission xmlns:sec="http://marklogic.com/xdmp/security"><sec:capability>read</sec:capability><sec:role-id>17997362789601553516</sec:role-id></sec:permission>, <sec:permission xmlns:sec="http://marklogic.com/xdmp/security"><sec:capability>update</sec:capability><sec:role-id>7981934846638917044</sec:role-id></sec:permission>, <sec:permission xmlns:sec="http://marklogic.com/xdmp/security"><sec:capability>execute</sec:capability><sec:role-id>17997362789601553516</sec:role-id></sec:permission>, <sec:permission xmlns:sec="http://marklogic.com/xdmp/security"><sec:capability>execute</sec:capability><sec:role-id>13041542794130379697</sec:role-id></sec:permission>, <sec:permission xmlns:sec="http://marklogic.com/xdmp/security"><sec:capability>update</sec:capability><sec:role-id>15080714410678341621</sec:role-id></sec:permission>, <sec:permission xmlns:sec="http://marklogic.com/xdmp/security"><sec:capability>read</sec:capability><sec:role-id>15080714410678341621</sec:role-id></sec:permission>), (), 0)
        at com.marklogic.hub.web.service.DataHubService.installUserModules(DataHubService.java:113)
        at com.marklogic.hub.web.service.DataHubService.installUserModulesAsync(DataHubService.java:100)
        at com.marklogic.hub.web.service.DataHubService$$FastClassBySpringCGLIB$$65ce96e0.invoke(<generated>)
        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:749)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
        at org.springframework.aop.interceptor.AsyncExecutionInterceptor.lambda$invoke$0(AsyncExecutionInterceptor.java:115)
        at java.util.concurrent.FutureTask.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
Caused by: com.marklogic.client.FailedRequestException: Local message: failed to apply resource at documents: Bad Request. Server Message: XDMP-CONFLICTINGUPDATES: ...

**Comment by fsnow** [comment] 2020-03-03 20:32
I should mention that I am running QuickStart with the --debug command line argument.

**Comment by akshaysonvane** [comment] 2020-03-06 16:14
Hi @fsnow, I tried reproducing the issue but did not run into the same error.
This is what I did:
Created a custom-hook module on the filesystem.
Added the right path in the mapping step using QS.
On saving the step the module got deployed.

Do I need to do something differently?

**Comment by rjrudin** [comment] 2021-03-08 03:36
Closing since it's QS

**Closed by rjrudin** 2021-03-08 03:36 UTC
