### ISSUE TITLE
I get TypeError: Can not read property 'toObject' of null at main during merging

### ISSUE THREAD

**Issue by venuiyengar** [marklogic/marklogic-data-hub#3586] opened 2020-02-16 23:54 UTC
*### Welcome Hub enthusiast!

Let's get the most out of this ticket, please fill out this template.

#### The issue

Short description of the problem:
Receiving null error while calling toObject
What behavior are you expecting?
I have a 2 step match and merge. During merge I get this error. I do see the summary document being created with no action. The permissions to the summary document is not set. I am setting the required project specific permissions as part of the step. If I run the flow steps as admin and I still get the same error.
What are the steps to reproduce the issue:
1) Create a flow with 3 steps, Ingestion, map and merge
2) Run the flow and the merge step fails with this error

![image](https://user-images.githubusercontent.com/10196200/74615265-341cdf00-50ed-11ea-9c83-8a4163b90fab.png)

#### Tech details

Which Operating System are you using? Windows 7

Which version of MarkLogic are you using? ML 10.0-2.1

Which version of the Data Hub are you using? 5.1

Is this a QuickStart UI bug? If so, which browser are you using?
Seen as part of the QuickStart. However, this seem to a back end issue accessing summary document to do the merge

#### The devil is in the details...

The message shown above has the source reference with line number

**Comment by rahulvudutala** [comment] 2020-02-19 16:39
@venuiyengar I couldn't reproduce the issue. I have done the following
1) Created entities, flows and mappings
2) The flow contains ingestion, mapping, match and merge steps
3) I have run the first 3 steps as flow-operator and have seen match summary document
4) I removed all the permissions on the document and added a permission to a role which has no inherited roles or privileges.
5) I have run the merge step with flow-operator user and didn't see the error. There were no merge docs after running as flow-operator. I tried with admin and I was able to see the merge docs in the final database.

Let me know if I should be reproducing the steps in a different way. It will also be helpful if there are any artifacts attached to debug the issue

**Comment by ryanjdew** [comment] 2020-02-20 22:12
@venuiyengar  Can you patch the merging step by placing the file [here](https://gist.github.com/ryanjdew/4a3d7da260759ae6331b5df7e29ec148) in your project at src/main/ml-modules/root/data-hub/5/builtins/steps/mastering/default/merging.sjs? After running the merging step, please review the ML app server logs for additional debugging information and let us know if the documents have been processed as expected.

**Comment by venuiyengar** [comment] 2020-02-21 01:32
@ryanjdew I patched and now it does not error out. However, it is failing here
content.uri - I added additional debugging, content has an array of uris in the summary document
and I am not sure that is what is expected, Logging the contents of content 

Essentially content.uri is undefined

2020-02-20 17:19:53.932 Info: {"message":"A match summary document for \"undefined\" was not found. The query used: {\"content\":\"[{\\\"uri\\\":\\\"/patients/urn:uuid:02b3a198-56f5-42e1-a3e1-34789717c9bc-patient.json\\\"}, {\\\"uri\\\":\\\"/patients/urn:uuid:f0edf2e5-bbcf-4b6f-9334-91deaed8ef4d-patient.json\\\"}]\"}","type":"warning","currentDateTime":"2020-02-20T17:19:53.6620331-08:00","user":"admin","serverID":"9174678257306847047","serverName":"eods-STAGING","dbID":"5905292349278716459","dbName":"eods-FINAL","modulesDbID":"8351940226642203699","modulesDbName":"eods-MODULES"}


2020-02-20 17:19:53.932 Info: {"message":"A match summary document for \"undefined\" was not found. The query used: {\"query\":\"{\\\"andQuery\\\":{\\\"queries\\\":[{\\\"rangeQuery\\\":{\\\"reference\\\":[{\\\"pathReference\\\":{\\\"pathExpression\\\":\\\"/matchSummary/URIsToProcess\\\", \\\"scalarType\\\":\\\"string\\\", \\\"collation\\\":\\\"http://marklogic.com/collation/\\\", \\\"nullable\\\":false}}], \\\"operator\\\":\\\"=\\\"}}, {\\\"collectionQuery\\\":{\\\"uris\\\":[\\\"datahubMasteringMatchSummary-Patient\\\"]}}]}}\"}","type":"warning","currentDateTime":"2020-02-20T17:19:53.6620331-08:00","user":"admin","serverID":"9174678257306847047","serverName":"eods-STAGING","dbID":"5905292349278716459","dbName":"eods-FINAL","modulesDbID":"8351940226642203699","modulesDbName":"eods-MODULES"}

**Comment by ryanjdew** [comment] 2020-02-21 22:33
@venuiyengar 
> content has an array of uris in the summary document

That sounds like the merging step has the "acceptsBatch" property set to true, when it should be false. Only the match step should have that value set to true.

**Comment by rjrudin** [comment] 2021-03-08 03:21
This appears fixed in merging.sjs; I don't see how the toObject() call could fail now, as a check is made first to make sure a match summary exists.

**Closed by rjrudin** 2021-03-08 03:21 UTC
