### ISSUE TITLE
[BUG] quickstart-Mapping fails for escape white space in URI

### ISSUE THREAD

**Issue by wpaven** [marklogic/marklogic-data-hub#4997] opened 2020-12-14 20:31 UTC
*### Welcome Hub enthusiast!

Let's get the most out of this ticket, please fill out this template.

#### The issue

Customer loaded data with ingest step from csv using QuickStart.
Location of data hub included whitespace
Default URIs created look like:   /C/MarkLogic/Projects/Matching%20Demo/Data/CDM/730e6e1e-6886-4cb6-a4b8-a47aadc34666.json

Where %20 escapes whitespace in quickstart UI

Path of data hub was: /C/MarkLogic/Projects/Matching Demo

Created entity in QS.
Created Mapping step in QS
See source document, Can map column from source to target entity.  Click test: No results but we see this error:

Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is com.marklogic.client.FailedRequestException: Local message: failed to apply resource at resources/mlMappingValidator: Internal Server Error. Server Message: JS-JAVASCRIPT: let instance = docNode.xpath('/*:envelope/(object-node("instance")|*:instance/(element() except *:info))'); -- Error running JavaScript request: TypeError: Cannot read property 'xpath' of null . See the MarkLogic server error log for further detail.] with root cause
com.marklogic.client.FailedRequestException: Local message: failed to apply resource at resources/mlMappingValidator: Internal Server Error. Server Message: JS-JAVASCRIPT: let instance = docNode.xpath('/*:envelope/(object-node("instance")|*:instance/(element() except *:info))'); -- Error running JavaScript request: TypeError: Cannot read property 'xpath' of null . See the MarkLogic server error log for further detail.

*****Turns out removing the whitespace from the URI fixes the problem.******

Short description of the problem:

What behavior are you expecting?

What are the steps to reproduce the issue:
1)
2)
3)

#### Tech details

Which Operating System are you using?  Windows 10

Which version of MarkLogic are you using? 10.0-5
Which version of the Data Hub are you using?  5.2.5

Is this a QuickStart UI bug? If so, which browser are you using?  chrome

#### The devil is in the details...

If possible, rerun the command with -d for debugging output and attach the output:

  **for quickstart:**  
  `java -jar marklogic-datahub-<version>.war  --debug  > myoutput.txt`

  **for gradle:**  
  `gradle mlYourCommand -debug > myoutput.txt`

**Comment by rjrudin** [comment] 2020-12-16 15:41
Will test this to reproduce outside of QS; sounds like a general mapping bug

**Comment by rjrudin** [comment] 2020-12-16 17:35
@wpaven I confirmed that this works both in Hub Central and from Gradle on the DHF develop branch. Pinging @sbayatpur to confirm, but since we do not plan any fixes for QS, I am closing this ticket.

**Closed by rjrudin** 2020-12-16 17:35 UTC
