### ISSUE TITLE
[BUG] Matching step fails for documents in temporal collection 

### ISSUE THREAD

**Issue by sashamitrovich** [marklogic/marklogic-data-hub#3858] opened 2020-04-22 09:48 UTC
*### Welcome Hub enthusiast!

Let's get the most out of this ticket, please fill out this template.

#### The issue

Short description of the problem:
Running the Matching step on documents in a temporal collection (with that collection specified as one of the target collections) fails with error "**Message: No matches for reference**" 

What behavior are you expecting?
Matching step runs successfully and updates the docs in the temporal collection.

What are the steps to reproduce the issue:
1) Documents in a temporal collection are available in the FINAL db, systemStart/systemEnd axis exists and is populated by MarkLogic. Documents have been created with a custom step (to put the systemStart and systemEnd properties in the headers and not in the instance i.e. entity).
2) Run Matching step with this definition:
<img width="1519" alt="Screenshot 2020-04-22 at 11 24 54" src="https://user-images.githubusercontent.com/15609655/79965138-f4c39380-848b-11ea-83b2-d4fa20c2d067.png">

3) Get error:
Message: No matches for reference

stack trace:
```XDMP-NOMATCH: xdmp.eval("\n const temporal = require(\"/MarkLogic/temporal.xqy\");\n\n...", {writeQueue:[{uri:"/datahub/5/mastering/match-summary/daf9f8e5-45db-4490-915d-bcabf...", value:{matchSummary:{URIsToProcess:["/fund/MASTERDATAREPORTS/00197e43-1660-4401-ab71-0df54e320c35.jso...", "/fund/MASTERDATAREPORTS/004bae11-f9de-4639-866a-ea2ad041a05d.jso...", "/fund/MASTERDATAREPORTS/00614c7a-aeca-4cca-8677-179e4c1668f6.jso...", ...], actionDetails:{/com.marklogic.smart-mastering/matcher/notifications/3924187260da09a9db190514a0ed57b5.xml:{action:"notify", threshold:"will-notify", uris:["/fund/MASTERDATAREPORTS/024182bb-f4e5-4551-a13a-8dae805c0e7a.jso...", "/fund/MASTERDATAREPORTS/0ce71b07-1df8-41f7-9e5b-4ba3b3988977.jso...", "/fund/MASTERDATAREPORTS/13c9b889-b81c-42f2-9500-ea2c0bc0757c.jso...", ...]}, /com.marklogic.smart-mastering/merged/7db8d84bcc3caa89f588ab57b3f5750f.json:{action:"merge", threshold:"will-merge", uris:["/fund/MASTERDATAREPORTS/022e3ca4-5335-4032-8596-15288b4030a9.jso...", "/fund/MASTERDATAREPORTS/03fe7bcf-416e-43fb-b9cf-66ff9599dee3.jso...", "/fund/MASTERDATAREPORTS/08ea6939-db39-4203-9d07-3fd94acae593.jso...", ...]}}}}, context:{collections:["datahubMasteringMatchSummary", "datahubMasteringMatchSummary-FundamentalInformation"], permissions:[{capability:"read", roleId:"7004461930022123088"}, {capability:"update", roleId:"7004461930022123088"}, {capability:"update", roleId:"5126952842460325403"}, ...], metadata:{datahubCreatedOn:"2020-04-22T09:18:14.918667Z", datahubCreatedBy:"flow-developer", datahubCreatedInFlow:"fund-mastering-match-merge", ...}}}], permissions:"xdmp.defaultPermissions()", baseCollections:["match-fund-fundamental-data", "FundamentalInformation", "temporal-collection", ...]}, {database:"14757146973405796850", commit:"auto", update:"true", ...}) -- No matches for cts.elementReference(fn.QName("","systemStart"),["type=dateTime"]) in ObjectNode({"matchSummary":{"URIsToProcess":["/fund/MASTERDATAREPORTS/00197e43-1660-4401-ab71-0df54e320c35.json", ...], ...}}) in /data-hub/5/impl/hub-utils.sjs, at 55:24, in writeDocuments() [javascript] in /data-hub/5/impl/flow.sjs, at 229:53, in runFlow() [javascript] in /marklogic.rest.resource/mlRunFlow/assets/resource.sjs, at 60:24, in post() [javascript] in /MarkLogic/rest-api/lib/extensions-util.sjs, at 93:29, in callExtension() [javascript] in /MarkLogic/rest-api/lib/extensions-util.sjs, at 111:9, in applyOnce() [javascript] in /MarkLogic/rest-api/lib/extensions-util.sjs, at 919:44, in xdmp:function(fn:QName("http://marklogic.com/rest-api/resource/mlRunFlow","post"), "/marklogic.rest.resource/mlRunFlow/assets/resource.xqy")(map:map(<map:map xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" .../>), map:map(<map:map xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" .../>), document{object-node{}}) [javascript] in /data-hub/5/rest-api/lib/extensions-util.xqy, at 919:44, in extut:call-service("mlRunFlow", "POST", xdmp:function(fn:QName("http://marklogic.com/rest-api/resource/mlRunFlow","post"), "/marklogic.rest.resource/mlRunFlow/assets/resource.xqy"), map:map(<map:map xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" .../>), map:map(<map:map xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" .../>), document{object-node{}}) [1.0-ml] $extension-name = "mlRunFlow" $method = "POST" $service = xdmp:function(fn:QName("http://marklogic.com/rest-api/resource/mlRunFlow","post"), "/marklogic.rest.resource/mlRunFlow/assets/resource.xqy") $context = map:map(<map:map xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" .../>) $service-params = map:map(<map:map xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" .../>) $input = document{object-node{}} in /data-hub/5/rest-api/lib/extensions-util.xqy, at 872:20, in function() as item()*() [1.0-ml] in /data-hub/5/rest-api/lib/extensions-util.xqy, in xdmp:invoke(function() as item()*, <options xmlns="xdmp:eval"><isolation>same-statement</isolation><ignore-amps>...</ignore-amps></options>) [1.0-ml] in /data-hub/5/rest-api/lib/extensions-util.xqy, at 870:12, in extut:invoke-service("mlRunFlow", "POST", "query", xdmp:function(fn:QName("http://marklogic.com/rest-api/resource/mlRunFlow","post"), "/marklogic.rest.resource/mlRunFlow/assets/resource.xqy"), map:map(<map:map xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" .../>), map:map(<map:map xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" .../>), document{object-node{}}, fn:false()) [1.0-ml] $extension-name = "mlRunFlow" $method = "POST" $default-txn-mode = "query" $service = xdmp:function(fn:QName("http://marklogic.com/rest-api/resource/mlRunFlow","post"), "/marklogic.rest.resource/mlRunFlow/assets/resource.xqy") $context = map:map(<map:map xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" .../>) $service-params = map:map(<map:map xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" .../>) $input = document{object-node{}} $in-txn = fn:false() $txn-curr = "query" $txn-mode = "query" in /data-hub/5/rest-api/models/resource-model-query.xqy, at 270:20, in rsrcmodqry:resource-post("mlRunFlow", map:map(<map:map xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" .../>), map:map(<map:map xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" .../>), document{object-node{}}, fn:false(), local:rsrcmod-callback#6) [1.0-ml] $resource-name = "mlRunFlow" $context = map:map(<map:map xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" .../>) $resource-params = map:map(<map:map xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" .../>) $input = document{object-node{}} $in-txn = fn:false() $responder = local:rsrcmod-callback#6 $service = xdmp:function(fn:QName("http://marklogic.com/rest-api/resource/mlRunFlow","post"), "/marklogic.rest.resource/mlRunFlow/assets/resource.xqy") in /data-hub/5/rest-api/models/resource-model-query.xqy, at 237:4, in rsrcmodqry:exec-post(map:map(<map:map xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" .../>), map:map(<map:map xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" .../>), document{object-node{}}, local:rsrcmod-callback#6) [1.0-ml] $headers = map:map(<map:map xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" .../>) $endpoint-params = map:map(<map:map xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" .../>) $input = document{object-node{}} $responder = local:rsrcmod-callback#6 in /data-hub/5/rest-api/endpoints/resource-service-query.xqy, at 79:8 [1.0-ml] $headers = map:map(<map:map xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" .../>) $method = "POST" $body = document{object-node{}} $params = map:map(<map:map xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" .../>) $extra-names = ()```

#### Tech details

Which Operating System are you using?
MacOS 10.15.4 (19E266)

Which version of MarkLogic are you using?
10.0-3 on Docker

Which version of the Data Hub are you using?
5.2.1

Is this a QuickStart UI bug? If so, which browser are you using?
No.

#### The devil is in the details...

If possible, rerun the command with -d for debugging output and attach the output:

  **for quickstart:**  
  `java -jar marklogic-datahub-<version>.war  --debug  > myoutput.txt`

  **for gradle:**  
  `gradle mlYourCommand -debug > myoutput.txt`

Attached document mentioned in the stack trace:
[:fund:MASTERDATAREPORTS:00197e43-1660-4401-ab71-0df54e320c35.json.zip](https://github.com/marklogic/marklogic-data-hub/files/4515187/fund.MASTERDATAREPORTS.00197e43-1660-4401-ab71-0df54e320c35.json.zip)

**Comment by srinathgit** [comment] 2020-04-22 17:08
Thanks @sashamitrovich for opening the ticket. I have opened https://project.marklogic.com/jira/browse/DHFPROD-4829. If possible, can you upload the datahub project using which we can reproduce the issue.

**Comment by sashamitrovich** [comment] 2020-06-02 09:45
[Archive.zip](https://github.com/marklogic/marklogic-data-hub/files/4716225/Archive.zip)

Attaching the project. 
To replicate: 
1) In the flow "funds-master-data", adjust the Ingestion step's "xetra-source" source folder to point to your local disks "...funds-demo/source/xetra" folder in the project
2)  In the flow "funds-master-data", run ONLY steps "xetra-source" and "xetra-harmonize"
3) verify you have documents in FINAL, in "temporal-collection" temporal collection
4) In the flow "fund-mastering-match-merge", run ONLY step "match-fund-fundamental-data"
5) That should fail, observe the error.

**Comment by akshaysonvane** [comment] 2020-06-05 20:41
Based on a conversation with @ryanjdew, it seems that Mastering is different from Matching. Matching creates intermediate documents, while mastering goes straight to altering the documents. We see this issue as the match summary document created by the matching step doesn't have systemStart and systemEnd properties and we are trying to write it to the temporal collection.

Removing the `temporal-collection` from the collection key in `match-fund-fundamental-data` step should resolve the issue. We can also get rid of `FundamentalInformation` collection since that is the source collection for the document.

Thus, the collection key would finally just include:
`"collections" : [ "match-fund-fundamental-data", "matched" ]`

**Comment by sashamitrovich** [comment] 2020-06-09 09:01
Thanks, I will try this.

A question related to this: I still want to use the temporal collection with the merge step. Will that work?

**Comment by rjrudin** [comment] 2021-03-08 16:57
Closing per comments in DHFPROD-4829

**Closed by rjrudin** 2021-03-08 16:57 UTC
