### ISSUE TITLE
Error when adding more than one XML element as an attachment

### ISSUE THREAD

**Issue by epilith** [marklogic/marklogic-data-hub#1573] opened 2018-11-22 10:01 UTC
#### The issue

Adding more than one XML element as an attachment causes an error.

The code in flow-lib.xqy tests whether an attachment is an XML element, and if it fails this test it is treated as JSON. Where there is a list of XML elements it fails this test so it is passed to the JSON handler.

#### Tech details

Which Operating System are you using? OSX

Which version of MarkLogic are you using? 9.0-7

Which version of the Data Hub Framework are you using? 4.0.2

Is this a QuickStart UI bug? No

#### The devil is in the details...

The code in question is the following:
`if(map:get($content, "$attachments") instance of element() or
                 map:get($content, "$attachments")/node() instance of element()) then
                map:get($content, "$attachments")
              else
                let $c := json:config("basic")
                let $_ := map:put($c,"whitespace" , "ignore" )
                return
                 json:transform-from-json(map:get($content, "$attachments"),$c)`

Ideally this code should loop over each item and test it so that a mix of both XML elements and JSON objects can be used together in a single harmonization flow.

**Comment by srinathgit** [comment] 2018-11-26 19:32
1. Let's consider a source document with more than one XML element. It contains comment and processing instruction
```
?xml-stylesheet  href = "mlstyle.css" type = "text/css"?>
<root>
<test type="unit">
<validtest>
<empid>123</empid>
<fullname>bob smith</fullname>
<monthlysalary>1000</monthlysalary>
</validtest>
</test>
</root>
<!--Copyright 2012-2018 MarkLogic Corporation-->
```
2. When this ingested through input flow (with 'useEs' set to false), the following envelope will be written to staging db

```
<envelope xmlns="http://marklogic.com/entity-services">
<headers>
</headers>
<triples>
</triples>
<instance>
<?xml-stylesheet  href = "mlstyle.css" type = "text/css"?>
<root>
<test type="unit">
<validtest>
<empid>123</empid>
<fullname>bob smith</fullname>
<monthlysalary>1000</monthlysalary>
</validtest>
</test>
</root>
<!--Copyright 2012-2018 MarkLogic Corporation-->
</instance>
<attachments>
</attachments>
</envelope>
```

3. After harmonization, in the harmonized document in the final db, by default the attachment element would contain the entire envelope from the staging db. The harmonized document would be

```
<?xml version="1.0" encoding="UTF-8"?>
<envelope xmlns="http://marklogic.com/entity-services">
   <headers />
   <triples />
   <instance>
      <info>
         <title>e2eentity</title>
         <version>0.0.1</version>
      </info>
      <e2eentity xmlns="">
         <id>123</id>
         <name>bob smith</name>
         <salary>1000</salary>
      </e2eentity>
   </instance>
   <attachments>
      <envelope>
         <headers />
         <triples />
         <instance>
            <?xml-stylesheet href = "mlstyle.css" type = "text/css"?>
            <root>
               <test type="unit">
                  <validtest>
                     <empid>123</empid>
                     <fullname>bob smith</fullname>
                     <monthlysalary>1000</monthlysalary>
                  </validtest>
               </test>
            </root>
            <!--
                 Copyright 2012-2018 MarkLogic Corporation 
                 -->
         </instance>
         <attachments />
      </envelope>
   </attachments>
</envelope>
```

4. This works fine out of the box. Having more than one XML element in the attachment is handled by "if(map:get($content, "$attachments") instance of element()" which returns true and hence the entire envelope element is included into <attachment>

5. Are you getting any errors when having more than one XML element in source document ? If so, can you please provide all the steps to reproduce the error ? I don't understand what you mean by "Ideally this code should loop over each item and test it so that a mix of both XML elements and JSON objects can be used together in a single harmonization flow."

**Comment by epilith** [comment] 2018-11-26 23:42
Hi,

Thanks for getting back to me on this. Firstly, in your example you are storing the entire envelope from the input flow as an attachment. This is not how the DHF is commonly being used (see for example the tutorial where order data is harmonized here: https://marklogic.github.io/marklogic-data-hub/tutorial/harmonizing-order-data/

In the tutorial the content from the input flow envelope is retrieved and stored in the $attachments property of the output of the harmonize content plugin. The full envelope is not used.

The test `if(map:get($content, "$attachments") instance of element()` fails when there is a list of elements in the $attributes key of the content map. This can be trivially demonstrated with the following code snippet in Query Console:

```
let $content := map:entry('$attachments', (<a/>, <b/>, <c/>))
return if(map:get($content, "$attachments") instance of element()) then "ELEMENT"
else "OTHER"
```

You will see that the query returns OTHER, which means the code in flow-lib.xqy will treat the list of XML elements as JSON.

By "Ideally this code should loop over each item and test it so that a mix of both XML elements and JSON objects can be used together in a single harmonization flow" I mean that the DHF should support cases where $attachments can contain both XML elements and JSON objects, to handle cases where a harmonization flow uses both XML data and JSON data as input. This will fail on the current version.

A simple loop could handle this (simplified here):

```
for $attachment in map:get($content, '$attachments')
  return if ($attachment instance of element()) then ...handle XML...
  else if ($attachment instance of object-node()) then ...handle JSON object...
  else ...handle other data types...
```

This will work equally well for both single XML elements, multiple XML elements, single JSON objects, multiple JSON objects.

**Comment by aebadirad** [comment] 2019-06-17 17:14
We've updated how this works in Data Hub 5.0:  you should now be able to handle multiple/single element/objects in both instance and attachments.

We also do capture the entire envelope as it was, so you can track what the delta was in your headers/triples/attachments. This should make it much easier to track things, including if you want to keep any 'legacy data' in your headers/triples carrying over.

So closing this out because you'll need to upgrade to 5.0 to make use of this new method, as this particular fix would be for 4.x.

**Closed by aebadirad** 2019-06-17 17:14 UTC
