### ISSUE TITLE
Error when flow sent via REST+DMSDK Java API has wrong case in flow name

### ISSUE THREAD

**Issue by damonfeldman** [marklogic/marklogic-data-hub#1473] opened 2018-10-30 00:03 UTC
#### The issue
A NiFi input flow had the wrong flow name, and it was not reported with a sensible error (despite there being missing flow logic in the code).

What behavior are you expecting?
"No such flow as: 'someflowname'" or similar message.

#### Tech details

Which version of MarkLogic are you using? 9.0-6
Which version of the Data Hub Framework are you using?  4.0.1
Is this a QuickStart UI bug?   No.

#### The devil is in the details...

stack in MarkLogic:
``
2018-10-29 17:04:49.323 Notice:+  $header-getter = map:map(<map:map xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" .../>)
2018-10-29 17:04:49.323 Notice:+  $body-getter = xdmp:get-request-part-headers#0
2018-10-29 17:04:49.323 Notice:+  $trans-name = xdmp:get-request-part-body#1
2018-10-29 17:04:49.323 Notice:+  $trans-params = "ml:sjsInputFlow"
2018-10-29 17:04:49.323 Notice:+  $forest-id = map:map(<map:map xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" .../>)
2018-10-29 17:04:49.323 Notice:+  $default-metadata = ()
2018-10-29 17:04:49.323 Notice:+  $document-metadata = ()
2018-10-29 17:04:49.323 Notice:+in /data-hub/4/rest-api/models/document-model-update.xqy, at 3759:8,
2018-10-29 17:04:49.323 Notice:+in docmodupd:write-bulk-documents(map:map(<map:map xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" .../>), xdmp:get-request-part-headers#0, xdmp:get-request-part-body#1) [1.0-ml]
2018-10-29 17:04:49.323 Notice:+  $params = map:map(<map:map xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" .../>)
2018-10-29 17:04:49.323 Notice:+  $header-getter = xdmp:get-request-part-headers#0
2018-10-29 17:04:49.323 Notice:+  $body-getter = xdmp:get-request-part-body#1
2018-10-29 17:04:49.323 Notice:+  $trans-name = "ml:sjsInputFlow"
2018-10-29 17:04:49.323 Notice:+  $trans-params = map:map(<map:map xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" .../>)
2018-10-29 17:04:49.323 Notice:+  $temporal-collection = ()
2018-10-29 17:04:49.323 Notice:+  $system-timestamp = ()
2018-10-29 17:04:49.323 Notice:+in /data-hub/4/rest-api/models/document-model-update.xqy, at 618:12,
2018-10-29 17:04:49.323 Notice:+in docmodupd:post-bulk-documents(map:map(<map:map xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" .../>), map:map(<map:map xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" .../>), map:map(<map:map xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" .../>...function...)) [1.0-ml]
2018-10-29 17:04:49.323 Notice:+  $headers = map:map(<map:map xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" .../>)
2018-10-29 17:04:49.323 Notice:+  $params = map:map(<map:map xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" .../>)
2018-10-29 17:04:49.323 Notice:+  $env = map:map(<map:map xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" .../>...function...)
2018-10-29 17:04:49.323 Notice:+  $header-getter = xdmp:get-request-part-headers#0
2018-10-29 17:04:49.323 Notice:+  $body-getter = xdmp:get-request-part-body#1
2018-10-29 17:04:49.323 Notice:+  $response-type = "application/xml"
2018-10-29 17:04:49.323 Notice:+in /data-hub/4/rest-api/endpoints/document-item-update.xqy, at 302:16 [1.0-ml]
2018-10-29 17:04:49.325 Info: Status 500: XDMP-AS: $src as node() -- Invalid coercion: null as node()
2018-10-29 17:04:49.326 Info: Status 500: XDMP-AS: $src as node() -- Invalid coercion: null as node()
2018-10-29 17:04:49.340 Notice: XDMP-AS: $src as node() -- Invalid coercion: null as node()
2018-10-29 17:04:49.340 Notice:+in /data-hub/4/impl/flow-lib.sjs, at 56:16, in getFlow() [javascript]
2018-10-29 17:04:49.340 Notice:+in /data-hub/4/transforms/run-sjs-flow.sjs, at 26:21, in transform() [javascript]
2018-10-29 17:04:49.340 Notice:+in /MarkLogic/rest-api/lib/extensions-util.sjs, at 93:29, in callExtension() [javascript]
2018-10-29 17:04:49.340 Notice:+in /MarkLogic/rest-api/lib/extensions-util.sjs, at 111:9, in applyOnce() [javascript]
2018-10-29 17:04:49.340 Notice:+in /MarkLogic/rest-api/lib/extensions-util.sjs, at 943:44,
2018-10-29 17:04:49.340 Notice:+in xdmp:function(fn:QName("http://marklogic.com/rest-api/transform/run-sjs-flow","transform"), "/data-hub/4/transforms/run-sjs-flow.xqy")(map:map(<map:map xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" .../>), map:map(<map:map xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" .../>), document{object-node{"BABYNET-834-RECORD":object-node{"B834-MAINT-TYPE-CODE":text{"991"}, ...}, ...}}) [javascript]
2018-10-29 17:04:49.340 Notice:+in /data-hub/4/rest-api/lib/extensions-util.xqy, at 943:44,
2018-10-29 17:04:49.340 Notice:+in extut:call-service("ml:sjsInputFlow", "TRANSFORM", xdmp:function(fn:QName("http://marklogic.com/rest-api/transform/run-sjs-flow","transform"), "/data-hub/4/transforms/run-sjs-flow.xqy"), map:map(<map:map xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" .../>), map:map(<map:map xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" .../>), document{object-node{"BABYNET-834-RECORD":object-node{"B834-MAINT-TYPE-CODE":text{"991"}, ...}, ...}}) [1.0-ml]
2018-10-29 17:04:49.340 Notice:+  $extension-name = "ml:sjsInputFlow"
2018-10-29 17:04:49.340 Notice:+  $method = "TRANSFORM"
```

NiFi parameter configuration:

![image](https://user-images.githubusercontent.com/700633/47687245-c24a1a80-dbb5-11e8-8d9b-e43f2cce75b7.png)

**Comment by damonfeldman** [comment] 2018-10-30 00:05
Image is not displaying for me, so note it uses ml:sjsInputFlow as the ServerTransform and mmis-834-pff as the flow name (entity name is member).

**Comment by aebadirad** [comment] 2019-06-17 18:17
Duplicate of #1589 and we are tracking it there, so closing this issue to consolidate.

**Closed by aebadirad** 2019-06-17 18:17 UTC
