### ISSUE TITLE
Undeploy errors due to extra app servers difficult to debug

### ISSUE THREAD

**Issue by damonfeldman** [marklogic/marklogic-data-hub#1774] opened 2019-01-22 12:52 UTC
Short description of the problem:
I tried to undeploy while an extra app server was present on the staging database, and it the nature of the error was not well reported.

Both quickstart and gradle undeploy errored out, with stacktrace saying only:

```

07:17:20.009 [http-nio-8080-exec-10] ERROR o.a.c.c.C.[.[.[.[dispatcherServlet] - Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is com.marklogic.quickstart.exception.DataHubException: Error in connecting to the Data Hub API with the following message: 400 Bad Request] with root cause
org.springframework.web.client.HttpClientErrorException: 400 Bad Request
```

the gradle --debug option gave more information:
```
07:17:07.023 [http-nio-8080-exec-10] INFO  c.m.h.d.c.DeployHubDatabaseCommand - Checking to see if data-hub-STAGING has subdatabases that need to be removed. Looking in folder: /Users/dfeldman/ProjectRepos/hubtestv4/src/main/ml-config/databases/subdatabases/data-hub-STAGING
2019-01-22 07:17:20.000 ERROR 21573 --- [io-8080-exec-10] c.m.rest.util.MgmtResponseErrorHandler   : Logging HTTP response body to assist with debugging: <error xmlns="http://marklogic.com/xdmp/error">
  <status-code>400</status-code>
  <status>Bad Request</status>
  <message-code>MANAGE-CONFLICTINGCONFIG</message-code>
  <message>MANAGE-CONFLICTINGCONFIG: (err:FOER0000) A conflict has been detected:  database data-hub-STAGING is in use</message>
</error>
```
however this still did not report how the database was in use. 

When I tried to manually delete the database, the server warned me of the extra app server, allowing me to manually delete it.

This is not terrible, but it would be nice to get the underlying error message rather than a "400 bad request" error up front.

#### Tech details

Which Operating System are you using?   Mac OSX

Which version of MarkLogic are you using?  9.0-7

Which version of the Data Hub Framework are you using?   4.1.1

**Comment by rjrudin** [comment] 2019-01-22 14:08
"-i" / "--info" will report the same error (--debug is almost never needed for debugging deployment issues, -i almost always gets the job done and is worth using all the time). 

For the error message - I agree about improving it, but I think that should be a change to the Manage API. ml-gradle could try to catch these errors and do additional work to figure out which app servers depend on the database, but I'm a little reluctant to put workarounds like that into ml-gradle when the root cause is an error message in the server that isn't as helpful as we'd like for it to be. 

Was the extra app server defined in the configuration files, or had it been added manually?

**Comment by aebadirad** [comment] 2019-02-28 03:57
@damonfeldman Could you log this as a bug within bugtrack against the manage API? This is unfortunately a root cause there, with a filter through ml-app-deployer (ml-gradle) to data hub both passing along the information.

**Comment by aebadirad** [comment] 2019-06-15 19:28
This is a manage API for MarkLogic, so closing here as Data Hub nor ml-gradle can report what it doesn't know about.

**Closed by aebadirad** 2019-06-15 19:28 UTC
Labels: better-errors
