### ISSUE TITLE
mlDHFVersion default property should represent the latest version

### ISSUE THREAD

**Issue by sastafford** [marklogic/marklogic-data-hub#1480] opened 2018-10-30 21:32 UTC
#### The issue

If I have a gradle.properties file that is missing the mlDHFVersion property then QuickStart will not install correctly.  The default property is 2.0.0  

#### Tech details

Which Operating System are you using? Windows

Which version of MarkLogic are you using? 9.0.7

Which version of the Data Hub Framework are you using? 4.0.1

Is this a QuickStart UI bug? If so, which browser are you using? No

**Comment by aebadirad** [comment] 2019-06-15 20:27
This is intentional and by design. It's prevent accidental upgrades without being checked into the project's version control. 

Though we will look to make this more graceful in the future with regards to quickstart. Closing for now.

**Closed by aebadirad** 2019-06-15 20:27 UTC
