### ISSUE TITLE
DHF 5.0.0: Clearing Database contents causes Document URI not found errors

### ISSUE THREAD

**Issue by prestonmcgowan** [marklogic/marklogic-data-hub#2497] opened 2019-05-13 19:12 UTC
#### The issue
While trying to determine a mapping and issue, I cleared the contents of my databases.
When I try to go back into the Manage Flow screen, I am presented with this error.
![image](https://user-images.githubusercontent.com/1315891/57647567-4764b200-7591-11e9-99f1-3d0f6b322464.png)

I was not able to see any sample data on the mapping screen given the provided URI is bad. 

I expected the Data Hub to present me with a suggested new URI to use for mapping since the old URI could not be found.

#### Tech details

Which Operating System are you using?
MacOS 10.14.4 (18E226)

Which version of MarkLogic are you using?
9.0-9

Which version of the Data Hub Framework are you using?
5.0.0

Is this a QuickStart UI bug? If so, which browser are you using?
I don't think so, but it is a UX issue.

**Comment by prestonmcgowan** [comment] 2019-05-13 19:17
Using QConsole, I explored my STAGING database and selected a new URI.
I put the new URI in the page and hit the check mark. 
The page did not refresh and show new data.
I refreshed the page. The document error was not shown, but neither was the new document's data.
I see DevTools called to the backend and received a response.

![image](https://user-images.githubusercontent.com/1315891/57647913-34061680-7592-11e9-9969-3ae847d9a78d.png)

**Comment by ayuwono** [comment] 2019-05-13 19:17
We have two issues reported on JIRA for this. The problem is with ingesting CSV, we are unable to generate unique URI (it's giving you UUID instead)

**Comment by prestonmcgowan** [comment] 2019-05-13 19:19
Ok.
Well, here is a screenshot of the dropdown too.
![image](https://user-images.githubusercontent.com/1315891/57648031-6e6fb380-7592-11e9-83e1-ff619a551c48.png)


Do we have a GitHub issue for this?

**Comment by aebadirad** [comment] 2019-06-17 17:30
Yes, #2483 is a clone of this at the root. So I'll close this one as the other has a ticket being tracked and worked on already.

**Closed by aebadirad** 2019-06-17 17:30 UTC
