### ISSUE TITLE
mlcp error while loading xml file using DataHub 3.0.0

### ISSUE THREAD

**Issue by sreehesh** [marklogic/marklogic-data-hub#1177] opened 2018-07-16 10:19 UTC
### Welcome Hub enthusiast!

Let's get the most out of this ticket.

#### The issue

Short description of the problem: when I am loading the through mlcp,using the custom transform.xqy, I am getting the following below error-
Exception caught while transforming _/commercial/upp/policyFeed_request_26345983916_94451881_05082018122028.xml: XDMP-AS: (err:XPTY0004) let $_must_run_in_query_mode as xs:unsignedLong := xdmp:request-timestamp() -- Invalid coercion: () as xs:unsignedLong
_

What behavior are you expecting?
It should load the files in to the db

#### Tech details

Which Operating System are you using?
Windows 7

Which version of MarkLogic are you using?
ML 9.0-6
Which version of the Data Hub Framework are you using?
Data Hub 3.0.0

Is this a QuickStart UI bug? If so, which browser are you using?
I have created entities using gradle task and running mlcp from cmd prompt.

 C:\Sreehesh\ML\mlcp-9.0.3\bin\mlcp.bat  import ^
-mode local ^
-host localhost ^
-port 8010 ^
-username admin ^
-password admin ^
-input_file_path C:\Sreehesh\workspace\UPP-MVP\ErieDataHubPolicy\input\commercial\testdata ^
-input_file_pattern ".*policyFeed_request.*xml" ^
-output_collections "commercial-upp-batch,commercial-upp-to-be-processed" ^
-output_permissions "rest-reader,read,rest-writer,update" ^
-output_uri_replace "/C:/Sreehesh/workspace/UPP-MVP/ErieDataHubPolicy/input/commercial/testdata,''" ^
-output_uri_prefix "/commercial/upp" ^
-transform_module "/modules/transforms/Policy/mlcp-flow-transform-commercial-upp.xqy" ^
-transform_namespace "http://marklogic.com/data-hub/mlcp-flow-transform-commercial-upp" ^
-transform_param "debug=0,mode=type,job=1,entity=Policy,flow=upp,flowType=input" ^
-thread_count 4 ^
-batch_size 10 

#### The devil is in the details...

If possible, rerun the command with -d for debugging output and attach the output:

  **for quickstart:**  
  `java -jar quickstart.war -d > myoutput.txt`

  **for gradle:**  
  `gradle mlYourCommand -d > myoutput.txt`

**Comment by sreehesh** [comment] 2018-07-16 10:42
I am able to resolve this using by adding mlcp option  -modules_root "/".

**Comment by popzip** [comment] 2018-07-20 18:13
Not urgent for 3.1 since there is a workaround. Not sure if documentation or code update needed to improve the experience so will leave open.

**Comment by bsrikan** [comment] 2018-07-26 22:05
Duplicate of #1148

**Comment by aebadirad** [comment] 2018-09-14 22:07
This is a duplicate, but also this shoudln't be an issue in 4.0.0 any longer, so closing this out.

**Closed by aebadirad** 2018-09-14 22:07 UTC
Labels: priority:low
