### ISSUE TITLE
[FEATURE] Add additional details to namespace prefix error

### ISSUE THREAD

**Issue by mikeburl** [marklogic/marklogic-data-hub#4732] opened 2020-10-17 22:41 UTC
**Is your feature request related to a problem? Please describe.**
We're running into a consistent error where one of our mappings or entities is slightly malformed but since we have so many and have multiple developers working in the same project it's time consuming to track down which mapping or entity is actually the source of the problem.  At the time we're getting an error, 'cannot read property "namespacePrefix" of undefined, which doesn't tell us which actual mapping or entity is causing it.

**What is the user-facing scenario that prompted this gap in functionality?**
This occurs when we run mlHubDeployUserArtifacts

**Describe the solution you'd like**
The error should also include the name of the file it was attempting to insert into MarkLogic.

**Describe alternatives you've considered**
At the time we have to delete entities/mappings one by one and attempt redeploying until we find where the error is located.

**Additional context**
Screenshot of the error we're seeing is attached
![Screenshot_2020-10-17 VMware Horizon](https://user-images.githubusercontent.com/55807824/96354777-5ade4b80-10a8-11eb-8304-2d92c7f66df7.png)

**Comment by rjrudin** [comment] 2020-10-18 00:25
@mikeburl Thanks for the report. Looking at the line number, I can verify that this was addressed by DHFPROD-5203 already for 5.3.0.

**Closed by rjrudin** 2020-10-18 00:25 UTC

**Comment by damonfeldman** [comment] 2020-11-06 15:22
Is there a workaround in 5.2 where we can debug the root cause in terms of which entity or mapping is invalid and why? E.g. some function to call with an entity or mapping on each item to narrow it down in qconsole, or a debug statement to add somewhere?

**Comment by rjrudin** [comment] 2020-11-06 15:24
The workaround would be to "touch" each mapping - e.g. via qconsole - until you find the one that fails. I believe that error is thrown by a trigger that generates the XSLT based on the mapping JSON.
