### ISSUE TITLE
Duplicate indices being created by QuickStart in entity-config/databases/final-database.json and staging-database.json

### ISSUE THREAD

**Issue by kmoralesml** [marklogic/marklogic-data-hub#570] opened 2017-11-14 16:48 UTC
[final-database.json.txt](https://github.com/marklogic-community/marklogic-data-hub/files/1471693/final-database.json.txt)
[staging-database.json.txt](https://github.com/marklogic-community/marklogic-data-hub/files/1471694/staging-database.json.txt)

#### The issue

Short description of the problem:
Duplicate indices being created by QuickStart in entity-config/databases/final-database.json and staging-database.json.  

What behavior are you expecting?
I expect QuickStart to NOT create duplicate indices when the user creates 2 entities, and each having the same property (intentional).

#### Tech details

Which Operating System are you using?
 * Windows 10
 * AWS Linux  (Linux ip-10-239-12-211 4.4.44-39.55.amzn1.x86_64 #1 SMP Mon Jan 30 18:15:53 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux)

Which version of MarkLogic are you using? Observed in
* 9.03
* 9.02

Which version of the Data Hub Framework are you using?
 * DHF 2.0 Final

Is this a QuickStart UI bug? If so, which browser are you using?
 * Duplicate indices observed through the use of QuickStart -- Chrome
 * Error observed occasionally when using gradle headless after creating the entities and adding the same properties on both entities (intentially stating that the 2 entities have same property)

#### The devil is in the details...

See attachments, sample entity-config/databases/final-database.json and staging-database.json
Renamed with .txt suffixes so that these can be attached to the issue.

Error observed on occasion:
    
    Error:
    > Task :hubPreInstallCheck
    com.marklogic.hub.PreInstallCheck@7c3c1335
    > Task :mlDeployApp
    Logging HTTP response body to assist with debugging: {"errorResponse":{"statusCode":"500", 
    "status":"Internal Server Error", "messageCode":"ADMIN-DUPLICATECONFIGITEM", 
    "message":"ADMIN-DUPLICATECONFIGITEM: (err:FOER0000) Database resource 'xxxx-data-
    hub-FINAL' already contains 'Database 'range-element-index''"}}

    FAILURE: Build failed with an exception.

    * What went wrong:
    Execution failed for task ':mlDeployApp'.
    > 500 Internal Server Error

**Comment by popzip** [comment] 2017-11-15 17:37
Will work on this as a part of https://github.com/marklogic-community/marklogic-data-hub/issues/348

**Comment by paxtonhare** [comment] 2017-11-15 17:43
@kmoralesml Why are we duplicating indexes?

**Comment by dmcassel** [comment] 2018-02-22 22:14
Handles duplicates from entity services as well as user-entered duplicates

**Comment by dmcassel** [comment] 2018-02-22 22:14
(Kasey) What is the scenario for ES-created dupes?

**Comment by dmcassel** [comment] 2018-02-22 22:14
Someone creates two entities, which share a name. The user creates an index on same-named properties within the two entities. Each entity knows that an index is needed; in merging the two, we're currently duplicating the index.

**Comment by aebadirad** [comment] 2018-08-16 03:50
Confirmed the issue is still present in latest develop. We'll need to dedup after merging the entity index settings together and before combining them with the other configs on index deploy.

**Comment by damonfeldman** [comment] 2018-10-31 14:05
The workaround is to manually modify the database configuration files.  NOTE: that if you update the entity service models, then you will have to manually update the database configuration files again.

**Comment by aebadirad** [comment] 2019-06-15 19:40
This is resolved in Data Hub 5.0.1, and now we deduplicate entity indexes properly.

**Closed by aebadirad** 2019-06-15 19:40 UTC
Labels: 2.0, 3.0, 4.0, BackLog, better-errors, bug, priority:medium
