### ISSUE TITLE
newAppServicesClient doesn't use mlAppServicesPort

### ISSUE THREAD

**Issue by grtjn** [marklogic/marklogic-data-hub#4562] opened 2020-09-14 13:45 UTC
Attempting to run following task fails when mlFinalPort is unavailable, while it is expected that this would run against mlAppServicesPort:

```
task undeployQcBrand(type: com.marklogic.gradle.task.ServerEvalTask) {
    group 'Deployment Branding'
    logger.info("Removing QueryConsole branding.")
    client = hubConfig.newAppServicesClient()
    xquery =
        "xquery version '1.0-ml';\n"+
        "xdmp:eval('"+
        "  xquery version \"1.0-ml\"; \n"+
        "  declare namespace env-ui = \"http://marklogic.com/environment-ui\"; \n"+
        "  let \$env-ui-node := \n"+
        "    fn:doc(\"/cluster-ui-settings.xml\")/env-ui:environment-ui \n"+
        "  return \n"+
        "    if (exists(\$env-ui-node)) then \n"+
        "      xdmp:node-replace(\$env-ui-node/env-ui:ui-active, <env-ui:ui-active>{fn:false()}</env-ui:ui-active>)\n"+
        "    else ()',\n"+
        "  (),\n"+
        "  <options xmlns='xdmp:eval'>\n"+
        "    <database>{xdmp:database('App-Services')}</database>\n"+
        "  </options>)"
}
```

Using DHF 5.2.3, against ML 10.0-3.

Manually overriding mlFinalPort from command-line to mlAppServicesPort makes this task proceed as expected, confirming it looks at the wrong port property.

**Comment by rjrudin** [comment] 2021-03-08 13:55
This may have been fixed via some other work for DHF 5.4.0, as I'm not able to reproduce it there. I created the following task:

```
task hey(type: com.marklogic.gradle.task.ServerEvalTask) {
    client = hubConfig.newAppServicesClient()
    javascript = "console.log('hey: ' + fn.currentDateTime())"
}
```

I ran this without any changes, and the logging was in the 8000 log file. 

I then disabled the final app server to double check, ran the task, and verified it still logged to the 8000 file.

I then included -PmlAppServicesPort=8010, ran the task, and verified it still logged to the 8000 file. 

I doubt we'd do a 5.2.x release to fix just this, so the solution is to use 5.4.0.

**Closed by rjrudin** 2021-03-08 13:55 UTC
