### ISSUE TITLE
Invalid JSON error but JSON appears correct

### ISSUE THREAD

**Issue by stuartMoorhouse** [marklogic/marklogic-data-hub#3187] opened 2019-11-04 17:28 UTC
I am running QuickStart 5.0.3. I am getting this error:

```
Local message: failed to apply resource at documents: Bad Request. Server Message: 
XDMP-JSONCHAR: xdmp:multipart-decode("c37e3af0-af92-406a-a1ba-73f2a3a19ad6", binary{"2d2d63333765336166302d616639322d343036612d613162612d373366326133..."})
 -- Unexpected character ':' in JSON at line 1 char 22
```

when I try to ingest the attached document using an ingest flow that as been written in, and is called from, QuickStart.

[98.nonpublicExecutionReportAcknowledgement.json.zip](https://github.com/marklogic/marklogic-data-hub/files/3805275/98.nonpublicExecutionReportAcknowledgement.json.zip)

Online JSON validators such as https://jsonformatter.curiousconcept.com/ report this document as valid.

**Comment by browda** [comment] 2019-11-04 22:35
I cannot reproduce the problem you're having from the sample code you've attached, but I also think that surrounding code may be at fault.  My guess is that the preceding record is the one at issue.

If this is indeed the first item (and from context, I doubt that it is) please let me know.  Thanks!

**Comment by stuartMoorhouse** [comment] 2019-11-05 10:33
Hi, 

It probably is the surounding code but I'm not sure what is happening. I've recreated the bug (with DHF 4.3.2 this time but it was also an issue with 5) and attached my project structure.

Thanks
[sm-dhf-bug.zip](https://github.com/marklogic/marklogic-data-hub/files/3808486/sm-dhf-bug.zip)

**Comment by hao1st** [comment] 2019-11-06 18:43
@stuartMoorhouse I happened to see your post and found the nonpublicExecutionReportAcknowledgement.json_998.json is not valid json even if you validate it online. I noticed there is a "," in the end of the file. After you remove it, the json should be valid one.

**Comment by wooldridge** [comment] 2019-11-06 18:54
@hao1st, nice catch. I also see that comma at the end of the file in the sm-dhf-bug.zip project folder under the data subfolder. But I don't see that comma in the first attached JSON file in this ticket, odd.

**Comment by browda** [comment] 2019-11-08 17:26
In general, what really happens is that an error in a prior json element can cause the error to be reported in a perfectly valid json element because that's when the perceived error occurs.  I reproduced this yesterday by omitting a quotation mark (") or a colon (:) and then attempting to ingest generated data following the general pattern in the original example.  The funny thing is that at least two online json parsers didn't flag the incorrect json as being incorrect, either.

**Comment by rjrudin** [comment] 2021-03-08 02:55
Closing as issue was resolved

**Closed by rjrudin** 2021-03-08 02:55 UTC
