### ISSUE TITLE
One staging data source to two different collections

### ISSUE THREAD

**Issue by radaniba** [marklogic/marklogic-data-hub#5862] opened 2021-07-04 13:09 UTC
Hi everyone,

Sorry this is not a bug or a feature question but rather a question.
I noticed that when I do a mapping from one collection in staging to a collection in final, and if I do another mapping step using the same staging collection, but having different mapping logic, my first mapping is replaced by the new one, rather than having both.

staging A -> mapping step 1 -> mapA1
staging A -> mapping step 2 -> mapA2

I want to have both mapA1 and mapA2 but with mapping it seems to be only 1-1

How can I use the same staging collection to create two mapping in Final database ?

Rad

**Comment by rahulvudutala** [comment] 2021-07-08 17:16
@radaniba Thank you for reaching out to us. It looks like the issue is resolved by the support team (https://help.marklogic.com/staff/Tickets/Ticket/View/32432). 
Feel free to close the ticket if the issue is resolved or reach out to us if you have more questions.

**Closed** 2021-07-08 17:18 UTC
