### ISSUE TITLE
Old entity name is still retained on property entities type

### ISSUE THREAD

**Issue by ayuwono** [marklogic/marklogic-data-hub#651] opened 2018-01-15 21:44 UTC
OS: Mac
Browser: Chrome
ML version: 9.0 (Jan 12)
DHF version: 2.0.2

Steps:
1) Create an entity with title "Test" and save it
2) Change the entity title of "Test" to "Test Bla", and save it
3) Edit entity "Test Bla" and add a property, click on the Type menu and you still see "Test" under Entities

Expected:
Should not see "Test" as it's already renamed to "Test Bla"

See screenshot attachment
![](https://user-images.githubusercontent.com/7096668/34962774-04e7e7a8-f9fa-11e7-8a98-81d6cd94b2ac.png)

┆Status: Closed

**Comment by dmcassel** [comment] 2018-04-04 18:39
➤ Alexander Ebadirad commented:

Ensure the entity name is changed on disk when it's modified on the quickstart GUI

[~mwooldri] to assess if the UI is behaving properly, if it is, DHF core or the quickstart spring boot rest tier is the issue.

**Comment by dmcassel** [comment] 2018-04-09 21:54
➤ Mike Wooldridge commented:

I cannot reproduce this on the current marklogic-data-hub develop branch (I'm on a Mac). When I add an entity property after changing the entity name, I see the changed entity name under the Type menu. 

[~ayuwono], can you check in your environment.

**Comment by dmcassel** [comment] 2018-04-12 23:44
➤ Aries Yuwono commented:

It's not reproducible on develop as on 04/12

**Comment by aebadirad** [comment] 2018-05-03 15:51
Fixed with release of 3.0.0

**Closed by aebadirad** 2018-05-03 15:51 UTC
Labels: Component:QuickStart, Fixed in Dev, bug, priority:high
