### ISSUE TITLE
cts.jsonPropertyWordQuery throws "your query returned an empty sequence" when the property value is like ""000A005BA0BED3EA"

### ISSUE THREAD

**Issue by chenfiona** [marklogic/marklogic-data-hub#3414] opened 2019-12-25 21:19 UTC
### Welcome Hub enthusiast!

Let's get the most out of this ticket.

#### The issue

Short description of the problem:
cts.jsonPropertyWordQuery throws "your query returned an empty sequence" when the property value is like ""000A005BA0BED3EA".

What behavior are you expecting?
cts.jsonPropertyWordQuery throws "your query returned an empty sequence" after data is ingested from Microsoft Excel Comma Separated Values File (.csv) as JSON document. Other properties can be searched without issue. 
I used mlcp ingest the data outside DH like import the data to Document db, but still get the empty result back. Tried different v5 or ML 9, still not returning any document. 

#### Tech details

Which Operating System are you using?
Win and Linux

Which version of MarkLogic are you using?
MarkLogic 10

Which version of Data Hub are you using?
v5

Is this a QuickStart UI bug? If so, which browser are you using?
No
#### The devil is in the details...

If possible, rerun the command with -d for debugging output and attach the output:

**Comment by rjrudin** [comment] 2019-12-26 02:45
In what context are you invoking cts.jsonPropertyWordQuery? Via qconsole? Or is this when running a flow? We need to know the steps to reproduce this.

**Comment by chenfiona** [comment] 2019-12-26 03:30
I first used DH5.1.0, ingest data and invoked cts.jsonPropertyWordQuery and it didn't return the expected doc. It returned the expected doc when I queried other properties.
So I mlcp import the data (outside DH) into Document DB, still didn't work.
Miraculously, I then used DH5.1.0 but started from scratch (in the Quick Start UI, I manually created the flows and steps) and load the data (I got the newest data sets). As for now, I can query using cts.jsonPropertyWordQuery for that particular property value like "0135F35499CD6C2A". So I managed to finish the data harmonisation. 
I haven't tested this outside DH. I mean I didn't test this in regular mlcp import into ML database.
But I am not sure if this is DH or ML database itself problem. Very strange.

**Comment by rjrudin** [comment] 2020-01-02 15:04
Where are you running queries - in qconsole? Like are you doing a cts.search with a cts.jsonPropertyWordQuery? I'm not clear on the "when" as to when this error is occuring. 

Also, you mention that you first used DH5.1.0, then used DH5.1.0 - is that correct, that you've only had this problem on DH 5.1.0?

**Comment by rjrudin** [comment] 2020-01-02 15:39
I just did a quick test of ingesting a document with a value of "000A005BA0BED3EA" and I verified that a cts.search with a cts.jsonPropertyWordQuery (or cts.jsonPropertyValueQuery) works correctly in qconsole. 

I noticed that in your title and description, you use two double quotes at the start - i.e. ""000A005BA0BED3EA" . Is that intentional - i.e. did the value in your CSV start with a double quote? But in your last comment, you just have "0135F35499CD6C2A", which is working fine for you. 

I am going to close this since this seems to be working fine for you. But if you're able to provide steps for reproducing this, please reopen it and include your sample data.

**Closed by rjrudin** 2020-01-02 15:39 UTC

**Comment by chenfiona** [comment] 2020-01-03 23:57
Hi, yes, I get it work. I find the root cause is the ELS.  
Thanks for your input!
