### ISSUE TITLE
DHF 5.2.1 on DHS Azure 1.1 - Temporal issues

### ISSUE THREAD

**Issue by rodgersandrew** [marklogic/marklogic-data-hub#4359] opened 2020-08-07 17:26 UTC
### Welcome Hub enthusiast!

Let's get the most out of this ticket.

#### The issue

Short description of the problem: temporal-admin privilege is not behaving as expected in DHS

What behavior are you expecting?
In local DHF, users with 'temporal-admin' privilege can view temporal axis/collections using temporal library and can see the corresponding definitions in data-hub-*-SCHEMAS database.

When executing a flow with a target database that is temporal, expected result is that documents loaded will behave temporally. Expected result outside of DHS: "return content" of a flow will adhere to the options of the target collection defined. If temporal collection as target, the document will be managed temporally. This is not happening in DHS, most likely due to some limitation in privileges of data-hub-developer for DHS. In my local DHF environment, I can reduce this exact behavior down to roles that contain the temporal-admin privilege but that privilege SHOULD exist in DHS under data-hub-developer, but it is not behaving the same way.  

#### Tech details

Which Operating System are you using?

Which version of MarkLogic are you using?
DHS Azure 1.1

Which version of Data Hub are you using?
DHF 5.2.1

#### The devil is in the details...

Initial debugging seems like the user executing the flow does not have necessary permissions to load the documents as temporal during flow execution. 

Executing temporal.documentInsert confirms that (1) the collection/axis exists and (2) that documents can be inserted and managed temporally.

**Comment by srinathgit** [comment] 2020-08-10 18:11
1. What is the version of datahub you are deploying locally and the one in DHS ? Is it 5.2.1 in both cases ? 
2. Can you provide a sample datahub project (along with a readme  file) on how to reproduce the issue ?

**Comment by rodgersandrew** [comment] 2020-08-10 18:53
> 1. What is the version of datahub you are deploying locally and the one in DHS ? Is it 5.2.1 in both cases ?
> 2. Can you provide a sample datahub project (along with a readme  file) on how to reproduce the issue ?

(1) 5.2.1 in both cases
(2) I will try to produce a smaller sample project for reproduction, I'd need to clean up some enterprise specific information.

**Comment by srinathgit** [comment] 2020-08-25 23:35
https://project.marklogic.com/jira/browse/DHFPROD-5735 has been opened to address this issue. This is a duplicate of support ticket # 29634

**Comment by kkanthet** [comment] 2021-03-05 20:55
Issue Fixed in 5.4.0 release

**Closed by kkanthet** 2021-03-05 20:55 UTC
