### ISSUE TITLE
[BUG] SM-ENTITY-PROPERTY-NOT-FOUND on Mastering step

### ISSUE THREAD

**Issue by rawalpuneet** [marklogic/marklogic-data-hub#3749] opened 2020-03-24 20:36 UTC
*### Welcome Hub enthusiast!

Let's get the most out of this ticket, please fill out this template.

#### The issue

Getting SM-ENTITY-PROPERTY-NOT-FOUND on running the mastering step. 

#### Tech details

Data Hub 5.1.0
Error on mastering step
Reproducible using QS and attached project

#### The devil is in the details...
see attached gradle project

[mastering-test.tar.gz](https://github.com/marklogic/marklogic-data-hub/files/4377550/mastering-test.tar.gz)

**Comment by akshaysonvane** [comment] 2020-03-30 21:45
Hi @rawalpuneet, I am unable to reproduce the issue.
I ran the MasterPatientFlow in the attached project using 
Data Hub QS 5.1.0
ML 10.0-3
I see 10,000 documents being processed in the mastering step with 514 merged docs.

What's the ML version for your setup?

**Comment by rawalpuneet** [comment] 2020-03-31 00:09
ML Version : 10.0-2.1
MacOsx
QS 5.1
--

**Comment by bgeorge11** [comment] 2020-05-19 05:12
@akshaysonvane  Could you find anything about this ? I faced the same problem and looks like this comes from the protected path definitions. I can probably show you in my hub.. Let me know..
If PII is defined in the entity, it worked fine. But a protected path which is not in entity did not pass the matching step.

**Comment by akshaysonvane** [comment] 2020-05-19 16:50
I failed to reproduce the issue on ML 10.0-2.1.
The issue disappeared for @rawalpuneet when he upgraded to ML 10.0-3

**Comment by bgeorge11** [comment] 2020-05-19 17:00
I am on 10.0.3.

**Comment by akshaysonvane** [comment] 2020-05-21 17:12
@bgeorge11 would it be possible for you to upload a DHF project so that the DH support engineers can reproduce the issue?

**Comment by bgeorge11** [comment] 2020-05-21 17:29
Ok.. I will do it today or tomorrow. Let me re-create myself a couple of times..

**Comment by rahulvudutala** [comment] 2020-05-22 16:40
@bgeorge11 I created a protected path for an entity property that is defined in the entity model, but not using the quick start. I was able to run the flow successfully. 
Once you can share your project, I will try to reproduce.

**Comment by rjrudin** [comment] 2021-03-08 16:59
Closed based on inability to reproduce and lack of response

**Closed by rjrudin** 2021-03-08 16:59 UTC
