### ISSUE TITLE
[BUG] parseDate mapping function returns "undefined, undefined"

### ISSUE THREAD

**Issue by rawalpuneet** [marklogic/marklogic-data-hub#3553] opened 2020-02-05 12:01 UTC
parseDate('DD-Mon-YYYY') is returns 'undefined' on screen. 

#### Tech details

MacOS, 
ML10
DH5.1

<img width="1283" alt="Screen Shot 2020-02-05 at 5 53 01 AM" src="https://user-images.githubusercontent.com/10471384/73839935-b992bc00-47dc-11ea-95ce-0da3a79421e3.png">

**Comment by rawalpuneet** [comment] 2020-02-05 12:10
digging further , i fount out that parseDate current don't support YY year format. so it's returning null. 

Error message should be more meaningful regardless.

**Comment by aebadirad** [comment] 2020-02-07 00:36
What kind of error message would you like to see? In the space where you're typing out the parse date?

**Comment by rawalpuneet** [comment] 2020-02-07 15:58
something to the effect of what formats are supported or just 'source format not supported'. Undefined made me think that it was an app error.

**Comment by aebadirad** [comment] 2020-02-07 22:57
That sounds reasonable, I'll hand it over to @sbayatpur as this sounds more borderline enhancement for usability than strictly a 'bug' (though I can understand how it might be taken that way)

**Comment by rjrudin** [comment] 2021-03-08 03:13
Closing as it's a dupe of #3953

**Closed by rjrudin** 2021-03-08 03:13 UTC
Labels: 5.0, Component:Declarative-Mapping, better-errors
