### ISSUE TITLE
Allow specifying flow options for input flows in quickstart

### ISSUE THREAD

**Issue by damonfeldman** [marklogic/marklogic-data-hub#503] opened 2017-09-08 19:43 UTC
This task is to add the ability to specify additional parameters for input flow runs from the quickstart GUI. Quickstart runs mlcp internally (as a linked .jar) and the mlcp transform_param may require some additional properties for certain input flows.

jobId is actually required for input flows, and will be generated as a GUID if missing, but sometimes the jobId must be specified as a particular value, so may warrant it's own quickstart input field.

The paramters should be appended to the end of the transform_param comma-separated param list.

**Comment by gduplantier** [comment] 2017-11-06 18:44
This should also apply when running MLCP from the command line and specifying transform params.

**Comment by paxtonhare** [comment] 2017-11-06 19:05
@gduplantier you can already do this from the command line: just add an options={"some":"json"} into the params.

**Comment by gduplantier** [comment] 2017-11-06 19:43
Ahh,  were is this documented? I would like to see an example, in particular how to quote and what to escape.

**Comment by gduplantier** [comment] 2017-11-08 02:20
I tested adding options={\"some\":\"json\"} to the transform params  and it works, but only with one parameter.  options={\"some1\":\"json1\", \"some2\":\"json2\"} gives an error.

**Comment by aebadirad** [comment] 2018-09-15 21:26
This is in, but we suffer from this #1097 so, closing this as this is actually a duplicate of #1097 (and we have documentation on it too) 

https://marklogic.github.io/marklogic-data-hub/ingest/mlcp/

**Closed by aebadirad** 2018-09-15 21:26 UTC
Labels: Component:QuickStart, Documentation, Enhancement, priority:medium
