### ISSUE TITLE
Spring batch example could not run due to missing transform as part of data hub 4.0.0

### ISSUE THREAD

**Issue by venuiyengar** [marklogic/marklogic-data-hub#1438] opened 2018-10-12 16:04 UTC
Short description of the problem: 
While running spring batch example to ingest customer, I am getting the error

> 16:48:54.793 [main] INFO  c.m.c.d.impl.WriteBatcherImpl - flushing 50 queued docs
> 16:48:56.341 [pool-1-thread-1] WARN  c.m.c.d.impl.WriteBatcherImpl - Error writing batch: com.marklogic.client.FailedRequestException: Local message:
failed to apply resource at documents: Bad Request. Server Message: RESTAPI-INVALIDREQ: (err:FOER0000) Invalid request:  reason: Extension run-flow or
 a dependency does not exist: XDMP-MODNOTFOUND: (err:XQST0059) Module /marklogic.rest.transform/run-flow/assets/transform.xqy not found
> 16:48:56.341 [main] INFO  c.m.hub.job.SqlDbToHubJobConfig - AFTER JOB

Apparently missing the REST API transform in staging modules database due to the path changes from 2.0 release.

#### Tech details

Which Operating System are you using? Windows OS

Which version of MarkLogic are you using? 9.0-6.2

Which version of the Data Hub Framework are you using? 4.0.0

Is this a QuickStart UI bug? If so, which browser are you using? NO

#### The devil is in the details...

If possible, rerun the command with -d for debugging output and attach the output:

  **for quickstart:**  
  `java -jar quickstart.war -d > myoutput.txt`
[myoutput.txt](https://github.com/marklogic/marklogic-data-hub/files/2473778/myoutput.txt)

  **for gradle:**  
  `gradle mlYourCommand -d > myoutput.txt`

**Comment by sastafford** [comment] 2018-10-15 16:07
@rahulvudutala - I put together some code to troubleshoot this issue.  See the test code in commit 
eb4e981.  I've stripped out any Spring Batch code.  Spring Batch is not the problem.  The problem is when I am pushing documents to the STAGING database via DMSDK.  When I apply a transform with DMSDK I'm seeing the following error in the logs.  What are the correct parameters to the ServerTransform object when using DMSDK?  

2018-10-15 16:00:07.034 Notice:+in /data-hub/4/rest-api/models/document-model-update.xqy, at 3759:8,
2018-10-15 16:00:07.034 Notice:+in docmodupd:write-bulk-documents(map:map(<map:map xmlns:xs="http://www.w3.org/2001/XMLSchema"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" .../>), xdmp:get-request-part-headers#0, xdmp:get-request-part-body#1) [1
.0-ml]
2018-10-15 16:00:07.034 Notice:+  $params = map:map(<map:map xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.
w3.org/2001/XMLSchema-instance" .../>)
2018-10-15 16:00:07.034 Notice:+  $header-getter = xdmp:get-request-part-headers#0
2018-10-15 16:00:07.034 Notice:+  $body-getter = xdmp:get-request-part-body#1
2018-10-15 16:00:07.034 Notice:+  $trans-name = "ml:inputFlow"
2018-10-15 16:00:07.034 Notice:+  $trans-params = map:map(<map:map xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http:
//www.w3.org/2001/XMLSchema-instance" .../>)
2018-10-15 16:00:07.034 Notice:+  $temporal-collection = ()
2018-10-15 16:00:07.034 Notice:+  $system-timestamp = ()
2018-10-15 16:00:07.034 Notice:+in /data-hub/4/rest-api/models/document-model-update.xqy, at 618:12,
2018-10-15 16:00:07.034 Notice:+in docmodupd:post-bulk-documents(map:map(<map:map xmlns:xs="http://www.w3.org/2001/XMLSchema" x
mlns:xsi="http://www.w3.org/2001/XMLSchema-instance" .../>), map:map(<map:map xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns
:xsi="http://www.w3.org/2001/XMLSchema-instance" .../>), map:map(<map:map xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xsi
="http://www.w3.org/2001/XMLSchema-instance" .../>...function...)) [1.0-ml]
2018-10-15 16:00:07.034 Notice:+  $headers = map:map(<map:map xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www
.w3.org/2001/XMLSchema-instance" .../>)
2018-10-15 16:00:07.034 Notice:+  $params = map:map(<map:map xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.
w3.org/2001/XMLSchema-instance" .../>)
2018-10-15 16:00:07.034 Notice:+  $env = map:map(<map:map xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.
org/2001/XMLSchema-instance" .../>...function...)
2018-10-15 16:00:07.034 Notice:+  $header-getter = xdmp:get-request-part-headers#0
2018-10-15 16:00:07.034 Notice:+  $body-getter = xdmp:get-request-part-body#1
2018-10-15 16:00:07.034 Notice:+  $response-type = "application/xml"
2018-10-15 16:00:07.034 Notice:+in /data-hub/4/rest-api/endpoints/document-item-update.xqy, at 302:16 [1.0-ml]
2018-10-15 16:00:07.038 Info: Status 500: error (MISSING_CURRENT_TRACE): fn.error(xs.QName("MISSING_CURRENT_TRACE")); --

**Comment by sastafford** [comment] 2018-10-15 16:30
The ServerTransform name needs to be either ml:sjsInputFlow or ml:inputFlow.  

https://marklogic.github.io/marklogic-data-hub/ingest/marklogic-client-api/

**Comment by aebadirad** [comment] 2019-06-15 19:19
This issue has been resolved by documentation for 4.x.

**Closed by aebadirad** 2019-06-15 19:19 UTC
