### ISSUE TITLE
One entity's indexes configurations clobber all the others'

### ISSUE THREAD

**Issue by mikrovvelle** [marklogic/marklogic-data-hub#711] opened 2018-02-02 13:33 UTC
#### The issue

In QuickStart (2.0.3), let's say I have two entities, each with a handful of string fields. If I do this:

1. Open the edit dialogue for "Entity-A"
2. Set two fields to be range-indexed (with the ⚡️ icon)
3. Close the edit dialogue.

I get a modal prompt---

> Saved. Update Indexes in MarkLogic?

Click "OK". So far so good. The two indexes are saved in my project code and visible in the ML Admin panel.

*But then*, I do *this*:

1. Open the edit dialogue for "Entity-B"
2. Set two (other) fields to be range-indexed (with the ⚡️ icon)
3. Close the edit dialogue.
4. Respond to the modal prompt about Updating the Indexes with "Yes"

Now there's a problem. The Indexes for "Entity-A" have disappeared from both my code and the ML Admin panel.

This happens both for Staging and for Final.

#### Tech details

- OS X, ML running on Linux (Docker)
- MarkLogic 9.0-3.1
- Data Hub Framework 2.0.3, but the project originated on 2.0.2
- Tested on
    - Chrome 63.0.3239.132
    - Safari 11.0.1 (13604.3.5)

#### The devil is in the details...

> If possible, rerun the command with -d for debugging output and attach the output:

I did; output attached.

┆Status: Done

**Comment by aebadirad** [comment] 2018-02-08 22:26
Confirmed on 2.0.3 dev. It's a quickstart UI bug - the entity controller is being too greedy when setting the indexes.

**Comment by popzip** [comment] 2018-03-13 03:17
Should be fixed in next release.

**Comment by dmcassel** [comment] 2018-03-15 22:19
➤ Kasey Alderete commented:

dupe.

**Comment by aebadirad** [comment] 2018-05-03 15:52
Fixed with release of 3.0.0

**Closed by aebadirad** 2018-05-03 15:52 UTC
Labels: 2.0, BackLog, Component:QuickStart, Fixed in Dev, bug, priority:medium
