### ISSUE TITLE
[BUG] Smart Mastering - Custom Protected Path causing error in Matching step.

### ISSUE THREAD

**Issue by bgeorge11** [marklogic/marklogic-data-hub#3997] opened 2020-05-27 02:35 UTC
A custom protected path (not defined in entity definition) is resulting in below error when matching step is run. 
Specified entity property not found (SM-ENTITY-PROPERTY-NOT-FOUND): givenName in /com.marklogic.smart-mastering/impl/sm-es-impl.xqy, at 136:12, in es-i.... 

Pls contact biju.george@marklogic.com for recreating the issue.

**Comment by bsrikan** [comment] 2020-05-28 17:13
@ryanjdew pinging you for comments.

**Comment by ryanjdew** [comment] 2020-05-28 20:42
This one is odd. I'll spend some time triaging.

**Comment by sbayatpur** [comment] 2020-06-09 22:54
https://project.marklogic.com/jira/browse/DHFPROD-5161

**Comment by ryanjdew** [comment] 2020-06-17 18:59
@bgeorge11 The issue stems from the protected path matching the "lastName" property in the entity model definition. This is interfering with the generation of triples describing the entity type properties and causes the "Specified entity property not found" message.

This can be avoided by specifying a protected path that only targets the "lastName" property of entity instances and not the model (e.g., "/envelope/instance/Customer/lastName"). 

I did file a bug with the MarkLogic server for the root cause of the misleading error message specifying "givenName". There is an issue where if even if one property in an entity type model is protected, the triples will not appear for any of the properties of that entity type model.

**Comment by kkanthet** [comment] 2021-03-05 21:02
Fixed in server 10.0-5

**Closed by kkanthet** 2021-03-05 21:02 UTC
Labels: Component:Smart-Mastering
