### ISSUE TITLE
[BUG] Smart Mastering Merge doesn't return merged doc

### ISSUE THREAD

**Issue by paxtonhare** [marklogic/marklogic-data-hub#4034] opened 2020-06-02 00:39 UTC
*### Welcome Hub enthusiast!

Let's get the most out of this ticket, please fill out this template.

#### The issue

When merging via the mlSmMerge rest extension the "mergedDocument" property that is returned does not contain the merged document as intended, but rather the prov data.

The offending code is here:

https://github.com/marklogic/marklogic-data-hub/blob/master/marklogic-data-hub/src/main/resources/ml-modules/services/mlSmMerge.sjs#L52

Seems like there are 2 documents with no uri: the prov and the merged doc. You can't assume the 0th one is the merged doc.

What behavior are you expecting?

I'm expecting the merged doc to be returned.

**Comment by paxtonhare** [comment] 2020-06-02 01:17
It might matter that I set preview to true

**Comment by paxtonhare** [comment] 2020-06-02 01:24
This seems to work well:

`'mergedDocument': results.documents.filter((doc) => !!doc.previousUri)[0]`

**Comment by ryanjdew** [comment] 2020-06-02 17:10
Marking as a duplicate of https://github.com/marklogic/marklogic-data-hub/issues/4000

**Closed by ryanjdew** 2020-06-02 17:10 UTC
Labels: bug, duplicate
