### ISSUE TITLE
[BUG] Score reductions were removed and no longer work

### ISSUE THREAD

**Issue by damonfeldman** [marklogic/marklogic-data-hub#3976] opened 2020-05-20 11:47 UTC
The origina design for Smart Mastering is to have arbitrary queries and arbitrary score reductions, customizable in code. 

That is, .sjs (or .xqy) custom functions could be added to expand the candidate list using the full power of MarkLogic query, and .sjs (or .xqy) custom functions could also be added to "filter" or reduce the list. 

This combination of an over-estimator (broad query) with a corrective filter allowed Smart Mastering (then called Agile Mastering) to cover all cases.

Unfortunately, this capability was removed (!) and replaced with a weaker notion of negative boost weight query. (see: https://github.com/marklogic-community/smart-mastering-core/commit/d583f3635645560fa68b55850ca2f31fef94506c#diff-c6be626d66f3e4c198c097732dc26b1f)

This needs to be put back to the original design to cover required use cases in some situations.

#### The issue

In particular, we cannot reduce based on incorrect or specific values. This includes reducing when the levenshtein distance between terms is large vs small. We can only use a match/non-match (or soundsalike/metaphone) to do the scoring.

Also, there is no reduce function for present-but-incorrect values. In many systems, missing data is common and should not contribute to a severe penalty, but incorrect data is a critical indicator of a non match (imagine person data that is nearly identical without socials (likely match) vs nearly identical but the SSN is present and different).
What behavior are you expecting?

**Comment by sbayatpur** [comment] 2020-05-26 21:36
Hi @damonfeldman, I'm hearing that it wasn’t removed, but was altered for performance reasons to use cts:query to determine the weight adjustment, where before the function was passed a node that detailed what was matched between documents after the initial cts:search with the reduce score being subtracted if the function returned true.
 
We believe that what you want to do should still be possible by constructing cts:queries. They can return any type of query including a cts:document-query.

**Comment by rjrudin** [comment] 2021-03-08 16:45
@damonfeldman  Per feedback from @fsnow , we are tracking this as a stretch goal for 5.5. At a high level, the concept may involve an optional module that a user can provide to further analyze a possible match before it's confirmed as a match. I am going to close this since we're tracking it internally via Wiki/JIRA.

**Closed by rjrudin** 2021-03-08 16:45 UTC
Labels: 5.0, Component:Smart-Mastering
