### ISSUE TITLE
Where to place error-handler.xqy rest-rewriter.xml for Data Hub Rest-API

### ISSUE THREAD

**Issue by coenquant** [marklogic/marklogic-data-hub#2001] opened 2019-03-13 09:36 UTC
### Welcome Hub enthusiast!

Let's get the most out of this ticket.

#### The issue

XML Parsing Error: no root element foundLocation message when trying to connect to REST-API for 
Staging Database Data HUB 
Issue is due to file not found !

What behavior are you expecting?

Connect to REST API like it did to FINAL Database Rest API.  

#### Tech details

Which Operating System are you using?
CENTOS7  (appliance used for Marklogic data hub)
Which version of MarkLogic are you using?
version 9 
Which version of the Data Hub Framework are you using?
4.1.1
Is this a QuickStart UI bug? If so, which browser are you using?
nope
#### The devil is in the details...

Actually it appears that if  you install/configure the quickstart  Data HUB It attend to set the path for REST API 
error handler
Url rewriter
error-handler.xqy
rest-rewriter.xml
to
/data-hub/4/  which does not exists (at least I cannot find it)

This is only for the Staging Database of the Data HUB
the FINAL Database for the Data HUB  point to 

/MarkLogic/rest-api/error-handler.xqy
/MarkLogic/rest-rewriter.xml

Which actually exists.

CAN SOMEONE tell me where those files should be put or what is the root for the REST-API Services for the Data HUB ?

Coen

If possible, rerun the command with -d for debugging output and attach the output:

  **for quickstart:**  
  `java -jar quickstart.war -d > myoutput.txt`

  **for gradle:**  
  `gradle mlYourCommand -d > myoutput.txt`

**Comment by kkanthet** [comment] 2019-03-13 18:17
@coenquant once you install DHF these are deployed into modules DB and these are not in filesystem. Hope that helps

**Comment by coenquant** [comment] 2019-03-14 07:00
thanks will check on that

**Comment by coenquant** [comment] 2019-03-14 07:49
Correct /data-hub/4 are in <your>-datahub modules database . still those files are not found in modules database of you current data-hub . mean error-handler.xqy and rest-rewriter.xml. They  should be available in that  the modules database of your current data-hub module database.  Mean after you used the quickstart.war  to configure the data-hub its not loading those 2 files in to your data-hub modules database.  Is this expected behavior and requires post configure actions , Also your data-hub final database is using /MarkLogic/rest-api/  .   Of course I can make the files available under modules data bases /data-hub/4 but what is best practice… I can either use /MarkLogic/rest-api/……. or put the files in to /data-hub/4 . Just want to understand the logic of this

**Comment by kkanthet** [comment] 2019-03-14 18:11
@coenquant  i installed QuickStart 4.1.1 on 9.0-8.2 ML server and when i use  query console and look into data-hub-MODULES DB i see "/data-hub/4/rest-api/error-handler.xqy" and "/data-hub/4/rest-api/rewriter.xml" deployed . 
Can you lets us the exact version of ML and i see you are using quickstart-4.1.1 and i used the same

**Comment by coenquant** [comment] 2019-03-15 06:46
I'm on 9.0-8.1 and I used quickstart-4.1.1 and 4.2.1  both with same issue.  I'm not using the default ports do since I'm running multiple hubs on same server (not all together same time) but all on different ports

**Comment by coenquant** [comment] 2019-03-15 13:17
I just update to 9.0-8.2 and installed a new datahub from scratch with 4.1.1 Still same issue
Not sure if the name of you data-hub or port are makin a difference. 
Btw I'm using the appliance VM.

**Comment by coenquant** [comment] 2019-03-19 12:15
[deb1_out.txt](https://github.com/marklogic/marklogic-data-hub/files/2983208/deb1_out.txt)

used java -jar quick-start-4.1.1.war -d --server.port=17099  > deb1_out.txt to start the quickstart ,  did do a fresh install

**Comment by rjrudin** [comment] 2021-03-08 19:58
I did a quick test using DHF 4.3.2 and verified that the rewriter and error handler are under /data-hub/4 in the modules database. Closing as cannot reproduce this issue.

**Closed by rjrudin** 2021-03-08 19:58 UTC
