### ISSUE TITLE
Critical deployment bugs

### ISSUE THREAD

**Issue by anthony-gray** [marklogic/marklogic-data-hub#2534] opened 2019-05-22 17:50 UTC
There are critical deployment bugs. mlLoadModules/mlReloadModules only works properly with deployments from scratch, database configurations that require a database restart timeout (e.g. TaskServer number of threads) causes an error due to broken session handling, and token replacement doesn't work (thus requiring hardcoding of softcoded/property values). These bugs result from the fact that data-hub’s deployment functionality is a buggy extension of ml-gradle.

**Comment by aebadirad** [comment] 2019-05-22 17:59
That's a lot to deconstruct here.

Can we get what version of data hub, marklogic, and a set of specific errors?

**Comment by anthony-gray** [comment] 2019-05-22 18:23
I was working with MarkLogic 9 and I think DataHub v4.0.3, though now I use MLCP and ml-gradle directly without DataHub. For database configurations that require a database restart timeout you can try to deploy ml-config/root/task-servers/TaskServer.json with {"threads": "32"}. For token replacement you can use a token in a module (e.g. if mlContentDatabaseName=eds-nosql-rdl property is in gradle.properties then use "%%mlContentDatabaseName%%" in a modules.xqy module, deploy it, and observe that the token isn't replaced. For mlLoadModules/mlReloadModules only works properly with deployments from scratch, just deploy from scratch (e.g. with a fresh MarkLogic/Data folder, then change a module, remove a different module, and add a new module, and rename an existing module, then run mlLoadModules/mlReloadModules and observe the results. ml-gradle by itself behaves properly in all these cases. DataHub does not.

**Comment by aebadirad** [comment] 2019-05-22 18:31
Please upgrade to the latest version of Data hub 4 (4.3.1). This should resolve your deployment issues, and please do report back if it does not. You'll find it to be a much better experience.

**Comment by anthony-gray** [comment] 2019-05-22 18:47
Please reproduce these issues in the latest version of Data hub 4 (4.3.1). This should reveal your deployment issues, and please do report back if not. You'll find it the same buggy experience.

**Comment by aebadirad** [comment] 2019-05-22 19:07
Alright, I'll ask @rjrudin to attempt to reproduce your issues as outlined in both 4.3.1 and 5.0.0.

**Comment by rjrudin** [comment] 2019-05-22 20:50
@anthony-gray I used the example project at https://github.com/marklogic/marklogic-data-hub/tree/master/examples/dhf4-with-tests to test out the issues you reported. That example project uses 4.1.0, though I did my testing with 4.3.1 since that's the latest version of 4.x (though I believe 4.1.0 and 4.3.1 should be identical in terms of deployment behavior, while 4.0.x had a number of issues). 

Here's what I found:

- If a change to the task server causes a restart, I believe it's ml-gradle/ml-app-deployer that's not waiting for a restart. I've opened a ticket to capture this - https://github.com/marklogic-community/ml-app-deployer/issues/362 . 
- I verified that token replacement in modules works in DHF, but "%%mlContentDatabaseName%%" is not a token in a DHF app. "%%mlFinalDbName%%" works.
- I could not produce any issues with loading or reloading modules while adding/modifying/renaming/deleting modules.

**Comment by anthony-gray** [comment] 2019-05-23 01:33
The problem is likely DHF for restart issue because ml-gradle by itself that uses ml-app-deployer works just fine.

Create a custom property named "abc" then do "%%abc%%". Verify the substitution by fn:doc’ing the module in Query Console.

I'm skeptical module reloading works properly for all the scenarios I mentioned using gradle mlLoadModules or gradle mlReloadModules because this was not my experience, but since I no longer use DHF...

**Comment by kkanthet** [comment] 2019-09-04 22:55
@anthony-gray  is this still an issue ? If not can we close it.

**Comment by rjrudin** [comment] 2021-03-07 14:27
Closing based on my analysis above, as I am confident these are no longer issues in DHF 5.x

**Closed by rjrudin** 2021-03-07 14:27 UTC
