### ISSUE TITLE
Job status not updating

### ISSUE THREAD

**Issue by damonfeldman** [marklogic/marklogic-data-hub#1412] opened 2018-10-09 12:25 UTC
#### The issue

Short description of the problem:
I'm not seeing the jobs status bar update consistently. Once it got stuck at 50%, once at 0%.

Observed so far on input flows.

#### Tech details

Which Operating System are you using?  OSX
Which version of MarkLogic are you using?   9.0-6
Which version of the Data Hub Framework are you using?  4.0.1
Is this a QuickStart UI bug? If so, which browser are you using?  Probably not. See java stack trace below. (Chrome)

#### The devil is in the details...
```
08:22:21.655 [SimpleAsyncTaskExecutor-2] ERROR o.s.a.i.SimpleAsyncUncaughtExceptionHandler - Unexpected error occurred invoking async method 'public void com.marklogic.quickstart.service.DataHubService.validateUserModules(com.marklogic.hub.HubConfig,com.marklogic.quickstart.listeners.ValidateListener)'.
com.marklogic.client.FailedRequestException: Local message: failed to read resource at resources/ml:validate: Internal Server Error. Server Message: XDMP-AS: (err:XPTY0004) $uri as xs:string -- Invalid coercion: () as xs:string . See the MarkLogic server error log for further detail.
	at com.marklogic.client.impl.OkHttpServices.checkStatus(OkHttpServices.java:4327)
	at com.marklogic.client.impl.OkHttpServices.getIteratedResourceImpl(OkHttpServices.java:3098)
	at com.marklogic.client.impl.OkHttpServices.getIteratedResource(OkHttpServices.java:3075)
	at com.marklogic.client.impl.ResourceServicesImpl.get(ResourceServicesImpl.java:61)
	at com.marklogic.client.impl.ResourceServicesImpl.get(ResourceServicesImpl.java:57)
	at com.marklogic.hub.validate.impl.EntitiesValidatorImpl.validateAll(EntitiesValidatorImpl.java:37)
	at com.marklogic.quickstart.service.DataHubService.validateUserModules(DataHubService.java:138)
	at com.marklogic.quickstart.service.DataHubService$$FastClassBySpringCGLIB$$4c244452.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:746)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.aop.interceptor.AsyncExecutionInterceptor.lambda$invoke$0(AsyncExecutionInterceptor.java:115)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)
2018-10-09 08:22:22.935 ERROR 21208 --- [      Thread-11] com.marklogic.hub.util.MlcpRunner        : /Library/Java/JavaVirtualMachines/jdk1.8.0
```
MarkLogic staff: ping me for a repository illustrating the issue.

**Comment by grechaw** [comment] 2018-10-09 20:50
Interesting looking issue.  I'll see who can take it on for a repro.

**Comment by aebadirad** [comment] 2019-06-15 20:39
Due to age, unless this can be reproduced, going to close it, otherwise please reopen issue.

**Closed by aebadirad** 2019-06-15 20:39 UTC
Labels: bug
