### ISSUE TITLE
Incorrect selected sources sorting order

### ISSUE THREAD

**Issue by sjcrook** [marklogic/marklogic-data-hub#3100] opened 2019-10-18 20:21 UTC
/com.marklogic.smart-mastering/survivorship/merging/standard.xqy, merging:standard function, $selected-sources.  The order by clause needs to be changed from...

order by $source-score descending, $source-dateTime descending

...to...

order by xs:integer($source-score) descending, $source-dateTime descending

in order for the sorting to work correctly.

**Comment by srinathgit** [comment] 2019-10-18 23:44
Just want to confirm , did you try running a mastering step and you see that the sorting order is incorrect ?

**Comment by sjcrook** [comment] 2019-10-20 15:42
Correct.

**Comment by srinathgit** [comment] 2019-10-21 18:46
Created https://project.marklogic.com/jira/browse/DHFPROD-3411

**Comment by srinathgit** [comment] 2019-11-19 05:13
@sjcrook ,
I am not able to reproduce the issue. I added sources and they always seem to be ordered correctly as expected.
```let $source-score := fn:number(fn:head(($property-spec/*:source-weights/*:source[(@name|*:name ) = $source/name]/(@weight|*:weight), 0)))```
converts the weights to xs:decimal and order by clause always seems to work. Can you provide an instance where it is not ordered correctly

**Comment by sjcrook** [comment] 2019-11-19 19:57
That's because in your code, $source-score is wrapped in fn:number which is correct.  In 5.0.3, it's not wrapped in a number so there's the possibility (which I ran into) of sorting the numbers alphanumerically resulting in incorrect results.

**Comment by srinathgit** [comment] 2019-11-19 20:10
Ok.. So, this issue should be fixed in 5.1.0

**Closed** 2019-11-19 22:35 UTC
Labels: bug
