### ISSUE TITLE
Entities deleted from quick-start UI persists in data-hub-FINAL database

### ISSUE THREAD

**Issue by rahulvudutala** [marklogic/marklogic-data-hub#1117] opened 2018-06-26 20:49 UTC
#### The issue

Short description of the problem:
The entities deleted on the quick-start UI still persist the {entity-name}.entity.json file.
When the project directory is cleaned (all the user-config directories, plugin directories) are deleted the {entity-name}.entity.json files exist in the data-hub-FINAL database 

Expected Behavior:
For an entity, which is deleted in the quick-start UI, the corresponding document for the deleted entity ({entity-name}.entity.json) should not be persisted in the data-hub-FINAL database

#### Tech details

Which Operating System are you using?
Mac OSX

Which version of MarkLogic are you using?
ML 9.0-20180620

Which version of the Data Hub Framework are you using?
DataHubFramework built from latest develop branch as of 06/26/18

Is this a QuickStart UI bug? If so, which browser are you using?
Google Chrome

Steps to reproduce:
1) Build the war file using the command "./gradlew build -x test" from the root of the marklogic-data-hub directory
2) From the same location, run the command "java -jar quick-start/build/libs/quick-start-3.1.0.war"
3) visit http://localhost:8080 in a browser and follow the steps.
4) In entities page, create two entities and delete one of them.
5) In Browse Data page, select the final database and the document of the deleted entity persists.

┆Attachments: <a href="https:&#x2F;&#x2F;project.marklogic.com&#x2F;jira&#x2F;secure&#x2F;attachment&#x2F;36128&#x2F;Entities+in+final+db.png">Entities in final db.png</a> | <a href="https:&#x2F;&#x2F;project.marklogic.com&#x2F;jira&#x2F;secure&#x2F;attachment&#x2F;36129&#x2F;Entities+Page.png">Entities Page.png</a>

**Comment by aebadirad** [comment] 2018-09-16 01:12
This is really a duplicate of #794 because they involve the same thing (entities in QS and stored in the final database aren't synced), so closing and will use that one.

**Closed by aebadirad** 2018-09-16 01:12 UTC
Labels: Component:QuickStart, bug
